#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Generate the engine's managed-identity vocabulary from the provider schema.

Every managed provider process must carry the session it belongs to and the
provider that owns the claim. Each launcher hand-wrote that block, so a new
launcher could simply omit it -- and several did. Cursor Helm exported a private
name for the session id (fixed 2026-08-24); OpenCode Helm and Codex Console
never set the owner tag; Cursor Console and OpenCode Console set no identity at
all.

The schema is the single source for who the providers are. This renders it into
an enum the compiler can enforce, so a provider added to the schema cannot be
silently missing from a match, and the identity key lists live in one place
instead of thirteen.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "schemas" / "managed_providers.yml"
OUTPUT = ROOT / "engine" / "src" / "managed_identity_contract.rs"

# The one hand-written registry in this epic, and it is hand-written because
# there is nothing to derive it from: no schema records which environment
# variables carry session identity, and inferring it from usage would relearn
# each launcher's mistakes as the specification. Adding a key here is the
# deliberate act of saying "this names a session, run, or launch."
#
# A provider process receives these from its own launcher or not at all -- never
# by inheritance from whatever managed session happened to spawn it.
# `LONGHOUSE_SESSION_ID` is retired: it is scrubbed and never set.
NEVER_INHERITED = [
    "LONGHOUSE_SESSION_ID",
    "LONGHOUSE_MANAGED_SESSION_ID",
    "LONGHOUSE_MANAGED_PROVIDER",
    "LONGHOUSE_RUN_ID",
    "LONGHOUSE_CHANNEL_SESSION_ID",
    "LONGHOUSE_CHANNEL_CWD",
    "LONGHOUSE_PROVIDER_SESSION_ID",
    "LONGHOUSE_COORDINATION_TOKEN",
    "LONGHOUSE_HOOK_URL",
    "LONGHOUSE_HOOK_TOKEN",
    "LONGHOUSE_CODEX_BRIDGE_TOKEN",
    "LONGHOUSE_PERMISSION_HOOK_ENABLED",
    "LONGHOUSE_LAUNCH_ACTOR",
    "LONGHOUSE_LAUNCH_SURFACE",
    "LONGHOUSE_CURSOR_LAUNCH_ID",
    "LONGHOUSE_CURSOR_REGISTRATION_READY",
    "LONGHOUSE_CURSOR_PRINT_MODE",
    "LONGHOUSE_ANTIGRAVITY_STATE_DIR",
    "LONGHOUSE_ANTIGRAVITY_INBOX_DIR",
]


def _providers() -> list[str]:
    payload = yaml.safe_load(SCHEMA.read_text(encoding="utf-8"))
    rows = payload.get("providers")
    if not isinstance(rows, list) or not rows:
        raise SystemExit(f"{SCHEMA} must contain a non-empty 'providers' list")
    names = [str(row["provider"]) for row in rows if row.get("launch_local")]
    if not names:
        raise SystemExit(f"{SCHEMA} declares no provider with launch_local: true")
    return sorted(names)


def _variant(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def render() -> str:
    providers = _providers()
    lines = [
        "//! Managed-identity vocabulary, generated from the provider schema.",
        "//!",
        "//! @generated by scripts/generate/managed_identity_contract_rs.py -- DO NOT EDIT.",
        "//! Source: schemas/managed_providers.yml",
        "//! Regenerate with `make generate-managed-identity`.",
        "",
        "#![allow(dead_code)]",
        "",
        "/// A provider Longhouse can launch. One variant per `launch_local` row in",
        "/// the schema, so a provider added there cannot be silently missing from a",
        "/// match arm.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]",
        "pub enum ManagedProvider {",
    ]
    for name in providers:
        lines.append(f"    /// `{name}`")
        lines.append(f"    {_variant(name)},")
    lines += [
        "}",
        "",
        "impl ManagedProvider {",
        "    /// The wire name. This is the value of `LONGHOUSE_MANAGED_PROVIDER`.",
        "    pub const fn as_str(self) -> &'static str {",
        "        match self {",
    ]
    for name in providers:
        lines.append(f'            ManagedProvider::{_variant(name)} => "{name}",')
    lines += [
        "        }",
        "    }",
        "}",
        "",
        "/// Every launchable provider, in schema order.",
        "pub const ALL_MANAGED_PROVIDERS: &[ManagedProvider] = &[",
    ]
    for name in providers:
        lines.append(f"    ManagedProvider::{_variant(name)},")
    lines += [
        "];",
        "",
        "/// Keys the overlay always sets on a managed provider process.",
        "pub const REQUIRED_IDENTITY_KEYS: &[&str] = &[",
        '    "LONGHOUSE_MANAGED_SESSION_ID",',
        '    "LONGHOUSE_MANAGED_PROVIDER",',
        "];",
        "",
        "/// Keys a provider process never inherits. The overlay scrubs all of them;",
        "/// a launcher then sets back only the ones it owns.",
        "pub const NEVER_INHERITED_KEYS: &[&str] = &[",
    ]
    for key in NEVER_INHERITED:
        lines.append(f'    "{key}",')
    lines += ["];", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != rendered:
            print(f"{OUTPUT} is stale. Run `make generate-managed-identity`.", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
