#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Generate the engine's wire-phase vocabulary from the managed phase contract.

Python reads `managed_phase_contract.json` at runtime, so it cannot drift. The
engine had no link to the contract at all -- only a comment pointing at it --
and every phase was a bare string literal. That is how `codex_exec` came to emit
`"tool"`, a phase no consumer knew, which cost the Console its activity axis.

The contract stays the single source; this renders it into consts the compiler
can enforce.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "server" / "zerg" / "config" / "managed_phase_contract.json"
OUTPUT = ROOT / "engine" / "src" / "managed_phase_contract.rs"


def _load_phases() -> list[dict]:
    payload = json.loads(CONTRACT.read_text(encoding="utf-8"))
    phases = payload.get("phases")
    if not isinstance(phases, list) or not phases:
        raise SystemExit(f"{CONTRACT} must contain a non-empty 'phases' array")
    return phases


def render() -> str:
    phases = _load_phases()
    wire = [item["raw_phase"] for item in phases if not item.get("local_health_only", False)]
    local_only = [item["raw_phase"] for item in phases if item.get("local_health_only", False)]

    lines: list[str] = [
        "//! Wire-phase vocabulary, generated from the managed phase contract.",
        "//!",
        "//! @generated by scripts/generate/managed_phase_contract_rs.py -- DO NOT EDIT.",
        "//! Source: server/zerg/config/managed_phase_contract.json",
        "//! Regenerate with `make generate-phase-contract`.",
        "",
        "#![allow(dead_code)]",
        "",
    ]

    for item in phases:
        raw = item["raw_phase"]
        scope = "local health only" if item.get("local_health_only", False) else "wire"
        lines.append(f"/// `{raw}` -- attention: {item['attention']} ({scope}).")
        lines.append(f'pub const PHASE_{raw.upper()}: &str = "{raw}";')
    lines.append("")

    rendered_wire = ", ".join(f"PHASE_{name.upper()}" for name in wire)
    lines += [
        "/// Phases an adapter may put on the wire. Ingest rejects anything else.",
        f"pub const WIRE_PHASES: &[&str] = &[{rendered_wire}];",
        "",
    ]

    rendered_local = ", ".join(f"PHASE_{name.upper()}" for name in local_only)
    lines += [
        "/// Phases that never cross the wire; they exist only in local health.",
        f"pub const LOCAL_HEALTH_ONLY_PHASES: &[&str] = &[{rendered_local}];",
        "",
        "/// Is this a phase an adapter is allowed to ship?",
        "pub fn is_wire_phase(value: &str) -> bool {",
        "    WIRE_PHASES.contains(&value)",
        "}",
        "",
    ]

    rendered_freshness = ", ".join(
        f'(PHASE_{item["raw_phase"].upper()}, {item["freshness_seconds"]})' for item in phases
    )
    lines += [
        "/// Freshness window per phase, in seconds.",
        "///",
        "/// Previously restated here, in `session_runtime.PHASE_FRESHNESS`, and in",
        "/// local health, kept aligned by a doc comment that had already gone stale.",
        f"pub const PHASE_FRESHNESS_SECONDS: &[(&str, i64)] = &[{rendered_freshness}];",
        "",
    ]

    return _rustfmt("\n".join(lines))


def _rustfmt(source: str) -> str:
    """Return the rustfmt-normalized form.

    The checked-in file must already be what rustfmt would produce, or the
    --check gate fails every time someone runs cargo fmt.
    """
    with tempfile.TemporaryDirectory() as scratch:
        staged = Path(scratch) / "managed_phase_contract.rs"
        staged.write_text(source, encoding="utf-8")
        result = subprocess.run(
            ["rustfmt", "--edition", "2021", str(staged)],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise SystemExit(f"rustfmt failed: {result.stderr.strip()}")
        return staged.read_text(encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in file is stale.")
    args = parser.parse_args()

    rendered = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""

    if args.check:
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run `make generate-phase-contract`", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} matches the contract")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
