/**
 * Worker Isolation Guardrail Test
 *
 * Verifies that the E2E Postgres schema isolation is working correctly.
 * Each worker ID routes to a separate schema (e2e_worker_X).
 *
 * IMPORTANT: Uses unique guardrail-only worker IDs to avoid colliding
 * with real parallel test workers (0-15).
 */

import { test as base, expect } from './fixtures';

// Use numeric worker IDs outside the normal range (0-15) to avoid collisions
// The E2E test setup only creates schemas for IDs 0-15, but also supports
// any numeric ID via dynamic schema creation in the DB routing layer.
// Note: Using string IDs like 'guardrail_a' doesn't work because schemas
// are only created for numeric worker IDs.
const WORKER_ID_A = '100';
const WORKER_ID_B = '101';

const backendUrl = `http://127.0.0.1:${process.env.BACKEND_PORT || '8001'}`;

base.describe('Schema Isolation Guardrail', () => {
  // Generate unique markers to identify our automations (name is auto-generated by backend).
  const uniqueMarker = `guardrail_${Date.now()}`;
  const markerA = `Automation_A_${uniqueMarker}`;
  const markerB = `Automation_B_${uniqueMarker}`;

  let requestA: Awaited<ReturnType<typeof base.request.newContext>>;
  let requestB: Awaited<ReturnType<typeof base.request.newContext>>;

  base.beforeAll(async ({ playwright }) => {
    // Create API contexts for two isolated workers
    requestA = await playwright.request.newContext({
      baseURL: backendUrl,
      extraHTTPHeaders: { 'X-Test-Worker': WORKER_ID_A },
    });
    requestB = await playwright.request.newContext({
      baseURL: backendUrl,
      extraHTTPHeaders: { 'X-Test-Worker': WORKER_ID_B },
    });
  });

  base.afterAll(async () => {
    // Clean up contexts
    await requestA?.dispose();
    await requestB?.dispose();
  });

  base('data in worker A is NOT visible in worker B', async () => {
    // Sanity: confirm the backend is routing each worker ID to a different schema
    const schemaAResp = await requestA.get('/api/admin/debug/db-schema');
    expect(schemaAResp.ok(), `Failed schema debug A: ${await schemaAResp.text()}`).toBeTruthy();
    const schemaA = await schemaAResp.json();

    const schemaBResp = await requestB.get('/api/admin/debug/db-schema');
    expect(schemaBResp.ok(), `Failed schema debug B: ${await schemaBResp.text()}`).toBeTruthy();
    const schemaB = await schemaBResp.json();

    expect(schemaA.db_path, `Worker A db debug: ${JSON.stringify(schemaA)}`).toBeTruthy();
    expect(schemaB.db_path, `Worker B db debug: ${JSON.stringify(schemaB)}`).toBeTruthy();
    expect(schemaA.db_path, `Expected different DBs but got same: A=${JSON.stringify(schemaA)} B=${JSON.stringify(schemaB)}`).not.toBe(
      schemaB.db_path
    );
    expect(schemaA.worker_id).toBe(WORKER_ID_A);
    expect(schemaB.worker_id).toBe(WORKER_ID_B);

    // Worker A: Create an automation with a unique marker in system_instructions.
    // (name field is auto-generated by backend, so we use system_instructions as marker)
    const createAResponse = await requestA.post('/api/automations', {
      data: {
        system_instructions: markerA,
        task_instructions: 'Test task',
        model: 'gpt-mock',
      },
    });
    expect(createAResponse.ok(), `Failed to create automation A: ${await createAResponse.text()}`).toBeTruthy();
    const createdAutomationA = await createAResponse.json();
    expect(createdAutomationA.system_instructions).toBe(markerA);

    // Worker B: Create an automation with a different unique marker.
    const createBResponse = await requestB.post('/api/automations', {
      data: {
        system_instructions: markerB,
        task_instructions: 'Test task',
        model: 'gpt-mock',
      },
    });
    expect(createBResponse.ok(), `Failed to create automation B: ${await createBResponse.text()}`).toBeTruthy();
    const createdAutomationB = await createBResponse.json();
    expect(createdAutomationB.system_instructions).toBe(markerB);

    // Worker A: List automations - should see automation A's marker, not B's.
    const listAResponse = await requestA.get('/api/automations');
    expect(listAResponse.ok()).toBeTruthy();
    const automationsA = await listAResponse.json();

    const instructionsA = automationsA.map((a: { system_instructions: string }) => a.system_instructions);
    expect(instructionsA).toContain(markerA);
    expect(instructionsA).not.toContain(markerB);

    // Worker B: List automations - should see automation B's marker, not A's.
    const listBResponse = await requestB.get('/api/automations');
    expect(listBResponse.ok()).toBeTruthy();
    const automationsB = await listBResponse.json();

    const instructionsB = automationsB.map((a: { system_instructions: string }) => a.system_instructions);
    expect(instructionsB).toContain(markerB);
    expect(instructionsB).not.toContain(markerA);

    console.log(`✅ Schema isolation verified: Worker A and B have separate data`);
  });
});
