"""Longhouse build identity loader.

One build-identity.json file, two explicit read modes. No fallback.

- Installed wheel: read via `importlib.resources.files("zerg") / "build_identity.json"`.
- Source run (make dev / uv run): the env var `LONGHOUSE_BUILD_IDENTITY_PATH`
  must point at the canonical `.build/build-identity.json` generated by
  `scripts/build/generate_build_identity.py`.

If neither applies, or the chosen source is missing, raise
`BuildIdentityMissing`. Never guess, never re-infer, never hardcode.

Display format (see docs/specs/release-and-build-identity.md):
- release channel:    "0.2.0 (b672fcca)"
- dev channel, clean: "0.2.0-dev+b672fcca"
- dev channel, dirty: "0.2.0-dev+b672fcca.dirty"
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources
from pathlib import Path

RESOURCE_PACKAGE = "zerg"
RESOURCE_NAME = "build_identity.json"
ENV_VAR = "LONGHOUSE_BUILD_IDENTITY_PATH"


class BuildIdentityMissing(RuntimeError):
    """Raised when build identity cannot be located. Always loud, never silent."""


@dataclass(frozen=True)
class BuildIdentity:
    version: str
    commit: str
    commit_short: str
    dirty: bool
    built_at: str
    channel: str

    @property
    def qualified_version(self) -> str:
        if self.channel == "release":
            return f"{self.version} ({self.commit_short})"
        suffix = f"{self.commit_short}.dirty" if self.dirty else self.commit_short
        return f"{self.version}-dev+{suffix}"

    def as_dict(self) -> dict:
        return asdict(self)


_ALLOWED_CHANNELS = ("dev", "release")


def _parse(raw: str, source: str) -> BuildIdentity:
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise BuildIdentityMissing(f"build identity at {source} is not valid JSON: {exc}") from exc
    try:
        version = payload["version"]
        commit = payload["commit"]
        commit_short = payload["commit_short"]
        dirty = payload["dirty"]
        built_at = payload["built_at"]
        channel = payload["channel"]
    except KeyError as exc:
        raise BuildIdentityMissing(f"build identity at {source} missing key {exc}") from exc
    if not isinstance(dirty, bool):
        raise BuildIdentityMissing(f"build identity at {source} has non-bool dirty={dirty!r}")
    if channel not in _ALLOWED_CHANNELS:
        raise BuildIdentityMissing(f"build identity at {source} has invalid channel={channel!r}; expected one of {_ALLOWED_CHANNELS}")
    for name, value in (("version", version), ("commit", commit), ("commit_short", commit_short), ("built_at", built_at)):
        if not isinstance(value, str) or not value:
            raise BuildIdentityMissing(f"build identity at {source} has invalid {name}={value!r}")
    return BuildIdentity(
        version=version,
        commit=commit,
        commit_short=commit_short,
        dirty=dirty,
        built_at=built_at,
        channel=channel,
    )


def _load_from_env(path_str: str) -> BuildIdentity:
    path = Path(path_str)
    if not path.is_file():
        raise BuildIdentityMissing(f"{ENV_VAR}={path_str} but no file exists there. " "Run scripts/build/generate_build_identity.py.")
    return _parse(path.read_text(encoding="utf-8"), source=str(path))


def _load_from_resource() -> BuildIdentity:
    try:
        ref = resources.files(RESOURCE_PACKAGE) / RESOURCE_NAME
    except ModuleNotFoundError as exc:
        raise BuildIdentityMissing(f"package {RESOURCE_PACKAGE!r} not found") from exc
    if not ref.is_file():
        raise BuildIdentityMissing(
            f"bundled resource {RESOURCE_PACKAGE}/{RESOURCE_NAME} is missing. "
            "This wheel was built without a build-identity.json — rebuild with "
            "scripts/build/generate_build_identity.py first."
        )
    return _parse(ref.read_text(encoding="utf-8"), source=f"{RESOURCE_PACKAGE}/{RESOURCE_NAME}")


def _load_uncached() -> BuildIdentity:
    env_path = os.environ.get(ENV_VAR)
    if env_path is not None:
        if not env_path.strip():
            raise BuildIdentityMissing(
                f"{ENV_VAR} is set but empty. Unset it to fall back to the bundled resource, "
                "or point it at a real .build/build-identity.json."
            )
        return _load_from_env(env_path)
    return _load_from_resource()


@lru_cache(maxsize=1)
def load() -> BuildIdentity:
    """Load the build identity for this process. Cached for the process lifetime."""
    return _load_uncached()


def reset_cache() -> None:
    """Clear the cached identity. Tests only."""
    load.cache_clear()
