"""Provider CLI ownership constants shared by CLI and local health surfaces."""

CLAUDE_BIN = "claude"
CODEX_BIN = "codex"
OPENCODE_BIN = "opencode"
ANTIGRAVITY_BIN = "agy"
CODEX_BIN_ENV = "LONGHOUSE_CODEX_BIN"
OPENCODE_BIN_ENV = "LONGHOUSE_OPENCODE_BIN"
ANTIGRAVITY_BIN_ENV = "LONGHOUSE_ANTIGRAVITY_BIN"
PROVIDER_CLI_BINARY_BY_PROVIDER = {
    "codex": CODEX_BIN,
    "claude": CLAUDE_BIN,
    "opencode": OPENCODE_BIN,
    "antigravity": ANTIGRAVITY_BIN,
}
PROVIDER_CLI_ENV_BY_PROVIDER = {
    "codex": CODEX_BIN_ENV,
    "claude": None,
    "opencode": OPENCODE_BIN_ENV,
    "antigravity": ANTIGRAVITY_BIN_ENV,
}
LEGACY_MANAGED_CODEX_LAUNCHER_MARKER = "# longhouse-managed-codex-launcher"
PROVIDER_CLI_SOURCE_BRIDGE_STATE = "bridge_state"
PROVIDER_CLI_SOURCE_ANTIGRAVITY_BIN_FLAG = "--agy-bin"
PROVIDER_CLI_SOURCE_CODEX_BIN_FLAG = "--codex-bin"
PROVIDER_CLI_SOURCE_OPENCODE_BIN_FLAG = "--opencode-bin"
PROVIDER_CLI_SOURCE_MISSING = "missing"
PROVIDER_CLI_SOURCE_PATH = "PATH"
PROVIDER_CLI_SOURCE_PROCESS = "process"
