#!/bin/sh
# Frontend entrypoint - generates runtime config.js from env vars
#
# For split deploy: Pass API_BASE_URL and WS_BASE_URL env vars
# For monolithic: Don't pass env vars, uses same-origin /api defaults

CONFIG_FILE="/usr/share/nginx/html/config.js"

# If cross-origin env vars are set, generate config.js for split deploy
if [ -n "$API_BASE_URL" ] || [ -n "$WS_BASE_URL" ]; then
  API="${API_BASE_URL:-/api}"
  WS="${WS_BASE_URL:-}"

  # Default WS to API URL with ws(s) protocol + /ws suffix if not set
  if [ -z "$WS" ]; then
    # Convert http(s) to ws(s) and append /ws if API ends with /api
    WS=$(echo "$API" | sed 's|^http|ws|')
    case "$WS" in
      */api) WS="${WS}/ws" ;;
    esac
  fi

  cat > "$CONFIG_FILE" << EOF
// Runtime configuration - generated by docker-entrypoint.sh
// Cross-origin mode for split deploy
window.API_BASE_URL = "${API}";
window.WS_BASE_URL = "${WS}";
console.log("Config: API=" + window.API_BASE_URL + " WS=" + window.WS_BASE_URL);
EOF

  echo "Generated config.js for split deploy: API=$API WS=$WS"
else
  echo "Using default config.js (same-origin mode)"
fi

# Start nginx
exec nginx -g "daemon off;"
