#!/bin/sh
# Frontend entrypoint - generates runtime config.js from env vars
#
# For split deploy: Pass API_BASE_URL and WS_BASE_URL env vars
# For monolithic: Don't pass env vars, uses same-origin /api defaults

CONFIG_FILE="/usr/share/nginx/html/config.js"
CSP_FILE="/etc/nginx/csp.conf"

# If cross-origin env vars are set, generate config.js for split deploy
if [ -n "$API_BASE_URL" ] || [ -n "$WS_BASE_URL" ]; then
  API="${API_BASE_URL:-/api}"
  WS="${WS_BASE_URL:-}"

  # Normalize: strip trailing slashes
  API="${API%/}"

  # Default WS to API URL with ws(s) protocol + /ws suffix if not set
  if [ -z "$WS" ]; then
    # Convert http(s) to ws(s) and append /ws if API ends with /api
    WS=$(echo "$API" | sed 's|^http|ws|')
    case "$WS" in
      */api) WS="${WS}/ws" ;;
    esac
  fi

  # Normalize WS: strip trailing slashes
  WS="${WS%/}"

  # Validate URL format - reject if contains control characters or newlines
  # This prevents JS injection via malformed env vars
  case "$API" in
    *[[:cntrl:]]*)
      echo "ERROR: API_BASE_URL contains control characters, rejecting"
      API="/api"
      ;;
  esac
  case "$WS" in
    *[[:cntrl:]]*)
      echo "ERROR: WS_BASE_URL contains control characters, rejecting"
      WS=""
      ;;
  esac

  # Escape special characters for JS string (quotes, backslashes)
  # This prevents XSS if env vars contain malicious content
  API_ESCAPED=$(printf '%s' "$API" | sed 's/\\/\\\\/g; s/"/\\"/g')
  WS_ESCAPED=$(printf '%s' "$WS" | sed 's/\\/\\\\/g; s/"/\\"/g')

  cat > "$CONFIG_FILE" << EOF
// Runtime configuration - generated by docker-entrypoint.sh
// Cross-origin mode for split deploy
window.API_BASE_URL = "${API_ESCAPED}";
window.WS_BASE_URL = "${WS_ESCAPED}";
console.log("Config: API=" + window.API_BASE_URL + " WS=" + window.WS_BASE_URL);
EOF

  echo "Generated config.js for split deploy: API=$API WS=$WS"
else
  echo "Using default config.js (same-origin mode)"
  API=""
  WS=""
fi

# Generate dynamic CSP based on API_BASE_URL and WS_BASE_URL
# Extract and validate domains (prevent header injection)
API_DOMAIN=""
WS_DOMAIN=""

# Extract API domain
if [ -n "$API" ]; then
  case "$API" in
    http://*|https://*)
      # Extract domain (strip protocol and path)
      API_DOMAIN=$(echo "$API" | sed 's|^https\?://||; s|/.*||')
      # Validate domain contains only allowed characters (alphanumeric, dash, dot, colon for port)
      case "$API_DOMAIN" in
        *[!a-zA-Z0-9.:-]*)
          echo "WARNING: API_BASE_URL contains invalid characters, CSP will use 'self' only"
          API_DOMAIN=""
          ;;
      esac
      ;;
    *)
      echo "WARNING: API_BASE_URL not a valid URL, CSP will use 'self' only"
      ;;
  esac
fi

# Extract WS domain (if different from API)
if [ -n "$WS" ]; then
  case "$WS" in
    ws://*|wss://*)
      WS_DOMAIN=$(echo "$WS" | sed 's|^wss\?://||; s|/.*||')
      # Validate domain
      case "$WS_DOMAIN" in
        *[!a-zA-Z0-9.:-]*)
          echo "WARNING: WS_BASE_URL contains invalid characters"
          WS_DOMAIN=""
          ;;
      esac
      ;;
  esac
fi

# Build connect-src with API and WS domains
CONNECT_SRC="'self' https://accounts.google.com https://analytics.drose.io https://api.openai.com wss://api.openai.com"
if [ -n "$API_DOMAIN" ]; then
  CONNECT_SRC="$CONNECT_SRC https://$API_DOMAIN wss://$API_DOMAIN"
fi
# Add WS domain if different from API domain
if [ -n "$WS_DOMAIN" ] && [ "$WS_DOMAIN" != "$API_DOMAIN" ]; then
  CONNECT_SRC="$CONNECT_SRC wss://$WS_DOMAIN"
fi

# Always create CSP file (even if empty API) to prevent nginx include failure
cat > "$CSP_FILE" << EOF
add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; connect-src $CONNECT_SRC; script-src 'self' https://accounts.google.com https://analytics.drose.io; style-src 'self' 'unsafe-inline' https://accounts.google.com https://fonts.googleapis.com https://api.fontshare.com; font-src 'self' https://fonts.gstatic.com https://cdn.fontshare.com; img-src 'self' data: https:; frame-src https://accounts.google.com;" always;
EOF

echo "Generated CSP config with connect-src: $CONNECT_SRC"

# Start nginx
exec nginx -g "daemon off;"
