#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: macos-build-developer-id-p12.sh --cert <path> --key <path> --password <password> [options]

Build a .p12 bundle from an Apple-issued Developer ID certificate and the
matching private key generated by macos-create-developer-id-csr.sh.

Options:
  --cert <path>               Apple-issued certificate (.cer DER or PEM).
  --key <path>                Private key PEM path.
  --password <password>       Password used to encrypt the output .p12.
  --out <path>                Output path (default: ~/.longhouse/release/macos-trust/developer-id.p12).
  --friendly-name <name>      Friendly name in the .p12 bundle (default: Longhouse Developer ID).
  -h, --help                  Show this help text.
EOF
}

require_value() {
  local flag="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "Missing value for $flag" >&2
    usage >&2
    exit 1
  fi
}

CERT_PATH=""
KEY_PATH=""
P12_PASSWORD=""
OUT_PATH="${HOME}/.longhouse/release/macos-trust/developer-id.p12"
FRIENDLY_NAME="Longhouse Developer ID"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cert)
      require_value "$1" "${2:-}"
      CERT_PATH="$2"
      shift 2
      ;;
    --key)
      require_value "$1" "${2:-}"
      KEY_PATH="$2"
      shift 2
      ;;
    --password)
      require_value "$1" "${2:-}"
      P12_PASSWORD="$2"
      shift 2
      ;;
    --out)
      require_value "$1" "${2:-}"
      OUT_PATH="$2"
      shift 2
      ;;
    --friendly-name)
      require_value "$1" "${2:-}"
      FRIENDLY_NAME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$CERT_PATH" || -z "$KEY_PATH" || -z "$P12_PASSWORD" ]]; then
  usage >&2
  exit 1
fi

if [[ ! -f "$CERT_PATH" ]]; then
  echo "Certificate not found: $CERT_PATH" >&2
  exit 1
fi

if [[ ! -f "$KEY_PATH" ]]; then
  echo "Private key not found: $KEY_PATH" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT_PATH")"

TEMP_CERT="$(mktemp "${TMPDIR:-/tmp}/longhouse-developer-id-cert.XXXXXX.pem")"
cleanup() {
  rm -f "$TEMP_CERT"
}
trap cleanup EXIT

if openssl x509 -in "$CERT_PATH" -noout >/dev/null 2>&1; then
  cp "$CERT_PATH" "$TEMP_CERT"
else
  openssl x509 -inform DER -in "$CERT_PATH" -out "$TEMP_CERT"
fi

openssl pkcs12 \
  -export \
  -inkey "$KEY_PATH" \
  -in "$TEMP_CERT" \
  -out "$OUT_PATH" \
  -passout "pass:${P12_PASSWORD}" \
  -name "$FRIENDLY_NAME"

chmod 600 "$OUT_PATH"

cat <<EOF
Created Developer ID bundle:
  p12: ${OUT_PATH}

Next:
  1. Confirm the signing identity string (for example: Developer ID Application: Your Name (TEAMID)).
  2. Create or confirm the Apple notarization credentials.
  3. Run scripts/release/macos-set-github-trust-secrets.sh to push the secrets to GitHub.
EOF
