import Foundation

// Generated by scripts/generate_managed_phase_contract_swift.py.
// Do not edit by hand.

enum ManagedPhaseContract {
    private static let exactAttention: [String: ManagedAttentionKind] = [
        "thinking": .working,
        "running": .working,
        "needs permission": .blocked,
        "ready": .idle,
        "stalled": .idle,
        "idle": .idle,
        "completed": .idle,
    ]

    private static let prefixAttention: [(prefix: String, attention: ManagedAttentionKind)] = [
        (prefix: "running ", attention: .working),
        (prefix: "blocked on ", attention: .blocked),
    ]

    static func attention(forDisplayPhase raw: String?) -> ManagedAttentionKind? {
        guard let normalized = raw?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased(),
            !normalized.isEmpty
        else {
            return nil
        }

        if let exact = exactAttention[normalized] {
            return exact
        }

        for rule in prefixAttention where normalized.hasPrefix(rule.prefix) {
            return rule.attention
        }

        return nil
    }
}
