import { brotliCompressSync, gzipSync } from "node:zlib";
import { mkdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { encodeFrames } from "../src/components/remote-scene/sceneCodec";
import { renderSceneFrame } from "../src/components/remote-scene/sceneRenderer";
import { SCENE_SPEC } from "../src/components/remote-scene/sceneSpec";

const root = path.resolve(import.meta.dir, "..");
const generatedDir = path.join(root, "src/components/remote-scene/generated");
const publicDir = path.join(root, "public/prototypes/remote-scene");
const dataPath = path.join(generatedDir, "sceneData.ts");
const contactSheetPath = path.join(publicDir, "contact-sheet.svg");
const statsPath = path.join(publicDir, "scene-stats.json");

mkdirSync(generatedDir, { recursive: true });
mkdirSync(publicDir, { recursive: true });

const frameCount = SCENE_SPEC.durationSeconds * SCENE_SPEC.fps;
const frames = Array.from({ length: frameCount }, (_, frameIndex) => renderSceneFrame(frameIndex));
const encodedFrames = encodeFrames(frames);
// Keep the generated module human-inspectable while avoiding an import-time
// dependency on the offline renderer.
const dataSourceWithConstants = `// Generated by web/scripts/generate-remote-scene.ts. Do not edit by hand.\n\n` +
  `const encodedFrames = ${JSON.stringify(encodedFrames)};\n\n` +
  `export const REMOTE_SCENE_DATA = {\n` +
  `  width: ${SCENE_SPEC.width},\n` +
  `  height: ${SCENE_SPEC.height},\n` +
  `  fps: ${SCENE_SPEC.fps},\n` +
  `  durationSeconds: ${SCENE_SPEC.durationSeconds},\n` +
  `  palette: ${JSON.stringify(SCENE_SPEC.palette, null, 2)},\n` +
  `  encodedFrames,\n` +
  `} as const;\n`;
writeFileSync(dataPath, dataSourceWithConstants);

const xml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const samples = Array.from({ length: 12 }, (_, index) => index * 6);
const cellWidth = 5;
const cellHeight = 6;
const panelWidth = SCENE_SPEC.width * cellWidth;
const panelHeight = SCENE_SPEC.height * cellHeight + 23;
const columns = 3;
const rows = Math.ceil(samples.length / columns);
const sheetWidth = columns * panelWidth;
const sheetHeight = rows * panelHeight;
const svg: string[] = [
  `<svg xmlns="http://www.w3.org/2000/svg" width="${sheetWidth}" height="${sheetHeight}" viewBox="0 0 ${sheetWidth} ${sheetHeight}">`,
  `<rect width="100%" height="100%" fill="#0d0908"/>`,
  `<style>text{font-family:"JetBrains Mono",monospace;font-size:${cellHeight}px;dominant-baseline:hanging;white-space:pre}</style>`,
];

for (let sampleIndex = 0; sampleIndex < samples.length; sampleIndex += 1) {
  const frameIndex = samples[sampleIndex];
  const originX = (sampleIndex % columns) * panelWidth;
  const originY = Math.floor(sampleIndex / columns) * panelHeight;
  svg.push(`<rect x="${originX}" y="${originY}" width="${panelWidth}" height="${panelHeight}" fill="#120b09" stroke="#3d3428"/>`);
  svg.push(`<text x="${originX + 8}" y="${originY + 7}" fill="#b5a48e">${(frameIndex / SCENE_SPEC.fps).toFixed(2)}s  /  frame ${frameIndex}</text>`);
  const frame = frames[frameIndex];
  for (let row = 0; row < SCENE_SPEC.height; row += 1) {
    let runStart = 0;
    while (runStart < SCENE_SPEC.width) {
      const tone = frame[row * SCENE_SPEC.width + runStart];
      let runEnd = runStart + 1;
      while (runEnd < SCENE_SPEC.width && frame[row * SCENE_SPEC.width + runEnd] === tone) runEnd += 1;
      const glyph = SCENE_SPEC.palette[tone].glyph.repeat(runEnd - runStart);
      svg.push(`<text x="${originX + runStart * cellWidth}" y="${originY + 19 + row * cellHeight}" fill="${SCENE_SPEC.palette[tone].color}">${xml(glyph)}</text>`);
      runStart = runEnd;
    }
  }
}
svg.push("</svg>");
writeFileSync(contactSheetPath, `${svg.join("\n")}\n`);

const dataBytes = Buffer.from(dataSourceWithConstants);
const stats = {
  format: "RLE palette frame stream",
  width: SCENE_SPEC.width,
  height: SCENE_SPEC.height,
  fps: SCENE_SPEC.fps,
  durationSeconds: SCENE_SPEC.durationSeconds,
  frameCount,
  paletteEntries: SCENE_SPEC.palette.length,
  encodedPayloadBytes: Buffer.byteLength(encodedFrames),
  runtimeAssetRawBytes: dataBytes.byteLength,
  runtimeAssetGzipBytes: gzipSync(dataBytes, { level: 9 }).byteLength,
  runtimeAssetBrotliBytes: brotliCompressSync(dataBytes).byteLength,
  contactSheetBytes: statSync(contactSheetPath).size,
  deterministic: true,
};
writeFileSync(statsPath, `${JSON.stringify(stats, null, 2)}\n`);

console.log(JSON.stringify({ dataPath, contactSheetPath, statsPath, ...stats }, null, 2));
