import { brotliCompressSync, gzipSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { encodeFrames } from "../src/components/remote-scene/sceneCodec";
import { renderSceneFrames } from "../src/components/remote-scene/sceneRenderer";
import { SCENE_SPEC, type SceneProfileKey } from "../src/components/remote-scene/sceneSpec";

const root = path.resolve(import.meta.dir, "..");
const generatedDir = path.join(root, "src/components/remote-scene/generated");
const dataPath = path.join(generatedDir, "sceneData.ts");
const framesPath = path.join(generatedDir, "sceneFrames.txt");
const MAX_GZIP_BYTES = 80 * 1024;
const MAX_BROTLI_BYTES = 55 * 1024;

mkdirSync(generatedDir, { recursive: true });

const profileKeys = Object.keys(SCENE_SPEC.profiles) as SceneProfileKey[];
const renderedProfiles = Object.fromEntries(profileKeys.map((profileKey) => {
  const frames = renderSceneFrames(profileKey);
  return [profileKey, { frames, encodedFrames: encodeFrames(frames) }];
})) as Record<SceneProfileKey, { frames: Uint8Array[]; encodedFrames: string }>;

const deterministic = profileKeys.every((profileKey) =>
  encodeFrames(renderSceneFrames(profileKey)) === renderedProfiles[profileKey].encodedFrames,
);
if (!deterministic) throw new Error("Remote scene renderer produced non-deterministic output");

const framesSource = `${profileKeys
  .map((profileKey) => renderedProfiles[profileKey].encodedFrames)
  .join("\n")}\n`;
writeFileSync(framesPath, framesSource);

const profileSource = profileKeys.map((profileKey, streamIndex) => {
  const profile = SCENE_SPEC.profiles[profileKey];
  return `    ${profileKey}: { width: ${profile.width}, height: ${profile.height}, streamIndex: ${streamIndex} },`;
}).join("\n");
const dataSource = `// Generated by web/scripts/generate-remote-scene.ts. Do not edit by hand.\n\n` +
  `import framesUrl from "./sceneFrames.txt?url";\n\n` +
  `export const REMOTE_SCENE_FRAMES_URL = framesUrl;\n\n` +
  `export const REMOTE_SCENE_DATA = {\n` +
  `  fps: ${SCENE_SPEC.fps},\n` +
  `  durationSeconds: ${SCENE_SPEC.durationSeconds},\n` +
  `  palette: ${JSON.stringify(SCENE_SPEC.palette, null, 2)},\n` +
  `  profiles: {\n${profileSource}\n  },\n` +
  `} as const;\n`;
writeFileSync(dataPath, dataSource);

const runtimeBytes = Buffer.from(`${dataSource}${framesSource}`);
const runtimeAssetGzipBytes = gzipSync(runtimeBytes, { level: 9 }).byteLength;
const runtimeAssetBrotliBytes = brotliCompressSync(runtimeBytes).byteLength;
if (runtimeAssetGzipBytes > MAX_GZIP_BYTES || runtimeAssetBrotliBytes > MAX_BROTLI_BYTES) {
  throw new Error(
    `Remote scene exceeds its compressed budget: ${runtimeAssetGzipBytes} gzip bytes, ${runtimeAssetBrotliBytes} Brotli bytes`,
  );
}

console.log(JSON.stringify({
  dataPath,
  framesPath,
  format: "RLE palette cinematic frame streams",
  fps: SCENE_SPEC.fps,
  durationSeconds: SCENE_SPEC.durationSeconds,
  frameCount: SCENE_SPEC.durationSeconds * SCENE_SPEC.fps,
  paletteEntries: SCENE_SPEC.palette.length,
  profiles: Object.fromEntries(profileKeys.map((profileKey) => {
    const profile = SCENE_SPEC.profiles[profileKey];
    return [profileKey, {
      width: profile.width,
      height: profile.height,
      encodedPayloadBytes: Buffer.byteLength(renderedProfiles[profileKey].encodedFrames),
    }];
  })),
  runtimeAssetRawBytes: runtimeBytes.byteLength,
  runtimeAssetGzipBytes,
  runtimeAssetBrotliBytes,
  deterministic,
}, null, 2));
