import { brotliCompressSync, gzipSync } from "node:zlib";
import { mkdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { encodeFrames } from "../src/components/remote-scene/sceneCodec";
import { renderSceneFrames } from "../src/components/remote-scene/sceneRenderer";
import { SCENE_SPEC, type SceneProfileKey } from "../src/components/remote-scene/sceneSpec";

const root = path.resolve(import.meta.dir, "..");
const generatedDir = path.join(root, "src/components/remote-scene/generated");
const publicDir = path.join(root, "public/prototypes/remote-scene");
const dataPath = path.join(generatedDir, "sceneData.ts");
const contactSheetPath = path.join(publicDir, "contact-sheet.svg");
const statsPath = path.join(publicDir, "scene-stats.json");
const MAX_GZIP_BYTES = 80 * 1024;
const MAX_BROTLI_BYTES = 55 * 1024;

mkdirSync(generatedDir, { recursive: true });
mkdirSync(publicDir, { recursive: true });

const profileKeys = Object.keys(SCENE_SPEC.profiles) as SceneProfileKey[];
const renderedProfiles = Object.fromEntries(profileKeys.map((profileKey) => {
  const frames = renderSceneFrames(profileKey);
  return [profileKey, { frames, encodedFrames: encodeFrames(frames) }];
})) as Record<SceneProfileKey, { frames: Uint8Array[]; encodedFrames: string }>;
const deterministic = profileKeys.every((profileKey) =>
  encodeFrames(renderSceneFrames(profileKey)) === renderedProfiles[profileKey].encodedFrames,
);
if (!deterministic) throw new Error("Remote scene renderer produced non-deterministic output");

const encodedConstants = profileKeys.map((profileKey) =>
  `const ${profileKey}EncodedFrames = ${JSON.stringify(renderedProfiles[profileKey].encodedFrames)};`,
).join("\n");
const profileSource = profileKeys.map((profileKey) => {
  const profile = SCENE_SPEC.profiles[profileKey];
  return `    ${profileKey}: { width: ${profile.width}, height: ${profile.height}, encodedFrames: ${profileKey}EncodedFrames },`;
}).join("\n");
const dataSourceWithConstants = `// Generated by web/scripts/generate-remote-scene.ts. Do not edit by hand.\n\n` +
  `${encodedConstants}\n\n` +
  `export const REMOTE_SCENE_DATA = {\n` +
  `  fps: ${SCENE_SPEC.fps},\n` +
  `  durationSeconds: ${SCENE_SPEC.durationSeconds},\n` +
  `  palette: ${JSON.stringify(SCENE_SPEC.palette, null, 2)},\n` +
  `  profiles: {\n${profileSource}\n  },\n` +
  `} as const;\n`;
writeFileSync(dataPath, dataSourceWithConstants);

const xml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const samples = Array.from({ length: 12 }, (_, index) => index * 12);
const columns = 3;
const cellWidth = 5;
const cellHeight = 6;
const sheetWidth = columns * SCENE_SPEC.profiles.desktop.width * cellWidth;
const sectionHeights = profileKeys.map((profileKey) => {
  const profile = SCENE_SPEC.profiles[profileKey];
  return 28 + Math.ceil(samples.length / columns) * (profile.height * cellHeight + 23);
});
const sheetHeight = sectionHeights.reduce((total, height) => total + height, 0);
const svg: string[] = [
  `<svg xmlns="http://www.w3.org/2000/svg" width="${sheetWidth}" height="${sheetHeight}" viewBox="0 0 ${sheetWidth} ${sheetHeight}">`,
  `<rect width="100%" height="100%" fill="#0d0908"/>`,
  `<style>text{font-family:"JetBrains Mono",monospace;font-size:${cellHeight}px;dominant-baseline:hanging;white-space:pre}</style>`,
];

let sectionOffsetY = 0;
for (let profileIndex = 0; profileIndex < profileKeys.length; profileIndex += 1) {
  const profileKey = profileKeys[profileIndex];
  const profile = SCENE_SPEC.profiles[profileKey];
  const frames = renderedProfiles[profileKey].frames;
  const panelWidth = profile.width * cellWidth;
  const panelHeight = profile.height * cellHeight + 23;
  svg.push(`<text x="8" y="${sectionOffsetY + 8}" fill="#c9a66b">${profileKey.toUpperCase()} CAMERA</text>`);
  for (let sampleIndex = 0; sampleIndex < samples.length; sampleIndex += 1) {
    const frameIndex = samples[sampleIndex];
    const originX = (sampleIndex % columns) * panelWidth;
    const originY = sectionOffsetY + 28 + Math.floor(sampleIndex / columns) * panelHeight;
    svg.push(`<rect x="${originX}" y="${originY}" width="${panelWidth}" height="${panelHeight}" fill="#120b09" stroke="#3d3428"/>`);
    svg.push(`<text x="${originX + 8}" y="${originY + 7}" fill="#b5a48e">${(frameIndex / SCENE_SPEC.fps).toFixed(2)}s  /  frame ${frameIndex}</text>`);
    const frame = frames[frameIndex];
    for (let row = 0; row < profile.height; row += 1) {
      let runStart = 0;
      while (runStart < profile.width) {
        const tone = frame[row * profile.width + runStart];
        let runEnd = runStart + 1;
        while (runEnd < profile.width && frame[row * profile.width + runEnd] === tone) runEnd += 1;
        const glyph = SCENE_SPEC.palette[tone].glyph.repeat(runEnd - runStart);
        svg.push(`<text x="${originX + runStart * cellWidth}" y="${originY + 19 + row * cellHeight}" fill="${SCENE_SPEC.palette[tone].color}">${xml(glyph)}</text>`);
        runStart = runEnd;
      }
    }
  }
  sectionOffsetY += sectionHeights[profileIndex];
}
svg.push("</svg>");
writeFileSync(contactSheetPath, `${svg.join("\n")}\n`);

const dataBytes = Buffer.from(dataSourceWithConstants);
const runtimeAssetGzipBytes = gzipSync(dataBytes, { level: 9 }).byteLength;
const runtimeAssetBrotliBytes = brotliCompressSync(dataBytes).byteLength;
if (runtimeAssetGzipBytes > MAX_GZIP_BYTES || runtimeAssetBrotliBytes > MAX_BROTLI_BYTES) {
  throw new Error(
    `Remote scene exceeds its compressed budget: ${runtimeAssetGzipBytes} gzip bytes, ${runtimeAssetBrotliBytes} Brotli bytes`,
  );
}
const stats = {
  format: "RLE palette cinematic frame streams",
  fps: SCENE_SPEC.fps,
  durationSeconds: SCENE_SPEC.durationSeconds,
  frameCount: SCENE_SPEC.durationSeconds * SCENE_SPEC.fps,
  paletteEntries: SCENE_SPEC.palette.length,
  profiles: Object.fromEntries(profileKeys.map((profileKey) => {
    const profile = SCENE_SPEC.profiles[profileKey];
    return [profileKey, {
      width: profile.width,
      height: profile.height,
      encodedPayloadBytes: Buffer.byteLength(renderedProfiles[profileKey].encodedFrames),
    }];
  })),
  runtimeAssetRawBytes: dataBytes.byteLength,
  runtimeAssetGzipBytes,
  runtimeAssetBrotliBytes,
  contactSheetBytes: statSync(contactSheetPath).size,
  deterministic,
};
writeFileSync(statsPath, `${JSON.stringify(stats, null, 2)}\n`);

console.log(JSON.stringify({ dataPath, contactSheetPath, statsPath, ...stats }, null, 2));
