"""Compatibility wrapper for the renamed desktop app helpers."""

from __future__ import annotations

from zerg.services import desktop_app as _desktop_app

DesktopAppStatus = _desktop_app.DesktopAppStatus
LocalHealthUiStatus = DesktopAppStatus
DEFAULT_REFRESH_SECONDS = _desktop_app.DEFAULT_REFRESH_SECONDS
LAUNCHD_LABEL = _desktop_app.LAUNCHD_LABEL
LEGACY_LAUNCHD_LABEL = _desktop_app.LEGACY_LAUNCHD_LABEL
build_local_health_arguments = _desktop_app.build_local_health_arguments
build_local_health_command = _desktop_app.build_local_health_command
build_snapshot_arguments = _desktop_app.build_snapshot_arguments
build_snapshot_command = _desktop_app.build_snapshot_command
default_install_desktop_app = _desktop_app.default_install_desktop_app
default_install_menubar = _desktop_app.default_install_menubar
get_desktop_app_service_info = _desktop_app.get_desktop_app_service_info
get_desktop_app_service_status = _desktop_app.get_desktop_app_service_status
get_menubar_service_info = _desktop_app.get_menubar_service_info
get_menubar_service_status = _desktop_app.get_menubar_service_status
install_desktop_app_service = _desktop_app.install_desktop_app_service
install_menubar_service = _desktop_app.install_menubar_service
uninstall_desktop_app_service = _desktop_app.uninstall_desktop_app_service
uninstall_menubar_service = _desktop_app.uninstall_menubar_service
