"""Single-writer serializer for SQLite.

SQLite permits only one writer at a time. When multiple background tasks
(ingest, presence flush, task queue, runner jobs) all compete for the write
lock via separate threads, `database is locked` errors and long waits result.

This module serializes ALL database writes through a single asyncio.Lock.
While one write executes, others wait in the queue. Reads are unaffected
(WAL mode allows unlimited concurrent readers).

Usage:
    from zerg.services.write_serializer import write_serializer

    # In async context:
    result = await write_serializer.execute(lambda db: do_writes(db))

    # With priority (lower = higher priority):
    await write_serializer.execute(fn, label="presence-flush")

Architecture:
    - A priority queue ensures one write at a time while letting
      interactive auth/ingest writes cut ahead of maintenance work
    - Each write runs in asyncio.to_thread() to avoid blocking the event loop
    - The write function receives a fresh Session, does its work, and returns
    - Session lifecycle (commit on success, rollback on error, close) is managed
      by the serializer
    - A dedicated single-connection write engine prevents pool contention
"""

from __future__ import annotations

import asyncio
import contextvars
import heapq
import logging
import os
import sqlite3
import sys
import threading
import time
import traceback
from collections import deque
from contextlib import contextmanager
from dataclasses import dataclass
from dataclasses import field
from datetime import datetime
from datetime import timezone
from typing import Any
from typing import Callable
from typing import Deque
from typing import Iterator
from typing import TypeVar

from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker

logger = logging.getLogger(__name__)

T = TypeVar("T")
_MISSING = object()
_TRUTHY_ENV = {"1", "true", "yes", "on"}

_DEFAULT_PRIORITY = 50
_LABEL_PRIORITIES: dict[str, int] = {
    # Interactive auth / token lifecycle should cut ahead of background churn.
    "refresh-session": 0,
    "device-token-create": 0,
    "device-token-revoke": 0,
    "managed-launch": 0,
    "launch-readiness": 0,
    "live-machine-control-operation": 0,
    "live-machine-control-result": 0,
    "live-machine-control-fail": 0,
    # Managed runtime events are the live UI truth lane and should cut ahead of
    # hook presence chatter when the machine is busy.
    "runtime-events": 5,
    "runtime-live": 3,
    "live-session-input-receipt": 3,
    "heartbeat-stamp": 5,
    # Live transcript deltas are user-visible and can be regenerated by the
    # archive lane, so keep them ahead of generic runtime observations. This
    # prevents a provider idle/needs_user phase from queueing ahead of the
    # transcript evidence that makes the turn visibly complete.
    "ingest-live": 4,
    # Transcript ingest is durable archive truth. It can trail runtime events,
    # but it should not sit behind high-volume presence retries.
    "runtime-observations": 5,
    # APNs/widget/queued-message side effects derived from runtime state should
    # not hold the hot runtime/transcript writer lane.
    "runtime-push": 25,
    "ingest": 45,
    # Daemon archive repair is intentionally behind health/control signals. It
    # can be regenerated from local files and should not make the machine look
    # offline while an old backlog drains.
    "ingest-scan": 45,
    "ingest-replay": 45,
    "runner-online": 10,
    "machine-control-reaper": 15,
    "session-turn-active": 15,
    "session-turn-terminal": 15,
    "presence": 20,
    "presence-flush": 20,
    "machine-presence": 30,
    "client-presence": 30,
    "runner-output": 20,
    "runner-job-complete": 20,
    "runner-job-error": 20,
    "runner-offline": 20,
    "machine-control-result": 10,
    "remote-launch-result": 10,
    "loop-thread": 25,
    "loop-thread-message": 25,
    "turn-review-create": 30,
    "turn-review-complete": 30,
    "turn-review-existing": 30,
    "wakeup-ledger": 35,
    "heartbeat": 40,
    "heartbeat-bookkeeping": 25,
    # Summary task bookkeeping and the final summary row update are small and
    # user-visible. Keep them ahead of archive ingest so a busy ingest storm
    # cannot pin the cold worker in "running" after a timeout.
    "summary": 7,
    "summary-title": 7,
    "server-fanout": 65,
    "archive-shadow-manifest": 65,
    "live-archive-drain": 65,
    "session-input-projection": 65,
    # Render beacons are forensic telemetry. Keep the persistence useful when
    # the system is healthy, but never let it outrank live transcript/runtime
    # writes when SQLite is under pressure.
    "client-render": 70,
    "live-preview-cleanup": 80,
    "task-claim": 7,
    "task-done": 7,
    "task-retry": 7,
    "task-continue": 7,
    "task-timeout": 7,
    "task-fail": 7,
    "summary-backfill": 60,
    "embeddings": 60,
    "projection-reconcile": 70,
    # Background queue maintenance is lowest priority.
    "task-resurrect": 85,
    "job-run": 90,
}


def _priority_for_label(label: str) -> int:
    normalized = (label or "").strip().lower()
    return _LABEL_PRIORITIES.get(normalized, _DEFAULT_PRIORITY)


@dataclass(order=True)
class _QueuedWrite:
    priority: int
    seq: int
    label: str = field(compare=False, default="")
    enqueued_at: float = field(compare=False, default=0.0)
    ready: asyncio.Future[None] = field(compare=False, repr=False, default=None)


_HISTOGRAM_WINDOW = 256
_DEFAULT_STACK_DUMP_AFTER_MS = 30_000.0
_DEFAULT_STACK_DUMP_RATE_LIMIT_MS = 30_000.0
_DEFAULT_INTERRUPT_AFTER_SECONDS = 120.0
_DEFAULT_INTERRUPT_GRACE_SECONDS = 15.0
_DEFAULT_TIMEOUT_INTERRUPT_GRACE_SECONDS = 2.0
_DEFAULT_BACKGROUND_FINALIZE_GRACE_SECONDS = 10.0
_DEFAULT_FAIRNESS_PROMOTE_AFTER_MS = 30_000.0


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or raw.strip() == "":
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None or raw.strip() == "":
        return default
    return raw.strip().lower() in _TRUTHY_ENV


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _sqlite_connection_from_session(db: Session) -> sqlite3.Connection | None:
    """Best-effort access to the DB-API sqlite connection owned by this Session."""

    try:
        sqlalchemy_connection = db.connection()
    except Exception:
        return None

    candidate: object = getattr(sqlalchemy_connection, "connection", None)
    seen: set[int] = set()
    while candidate is not None and id(candidate) not in seen:
        if isinstance(candidate, sqlite3.Connection):
            return candidate
        seen.add(id(candidate))
        next_candidate = getattr(candidate, "driver_connection", None)
        if next_candidate is None:
            next_candidate = getattr(candidate, "connection", None)
        candidate = next_candidate
    return None


def _looks_like_sqlite_interrupt(exc: BaseException) -> bool:
    if isinstance(exc, sqlite3.OperationalError) and "interrupted" in str(exc).lower():
        return True
    orig = getattr(exc, "orig", None)
    if isinstance(orig, BaseException) and _looks_like_sqlite_interrupt(orig):
        return True
    return False


@dataclass
class _LabelHistogram:
    """Rolling per-label timing window. Bounded deque -> exact percentiles."""

    queue_wait_ms: Deque[float] = field(default_factory=lambda: deque(maxlen=_HISTOGRAM_WINDOW))
    exec_ms: Deque[float] = field(default_factory=lambda: deque(maxlen=_HISTOGRAM_WINDOW))


@dataclass
class WriteStats:
    """Cumulative write serializer statistics."""

    total_writes: int = 0
    total_queue_wait_ms: float = 0
    total_exec_ms: float = 0
    max_queue_wait_ms: float = 0
    max_exec_ms: float = 0
    errors: int = 0
    _label_counts: dict[str, int] = field(default_factory=dict)
    _label_histograms: dict[str, _LabelHistogram] = field(default_factory=dict)

    def record_sample(self, label: str, queue_wait_ms: float, exec_ms: float) -> None:
        key = label or "unlabeled"
        hist = self._label_histograms.get(key)
        if hist is None:
            hist = _LabelHistogram()
            self._label_histograms[key] = hist
        hist.queue_wait_ms.append(queue_wait_ms)
        hist.exec_ms.append(exec_ms)


def _percentiles(samples: Deque[float]) -> dict[str, float]:
    """Return p50/p95/p99 of an unsorted deque. Empty -> zeros."""
    if not samples:
        return {"p50": 0.0, "p95": 0.0, "p99": 0.0, "n": 0}
    sorted_samples = sorted(samples)
    n = len(sorted_samples)

    def _pct(p: float) -> float:
        idx = min(n - 1, max(0, int(round((p / 100.0) * (n - 1)))))
        return round(sorted_samples[idx], 1)

    return {"p50": _pct(50), "p95": _pct(95), "p99": _pct(99), "n": n}


@dataclass
class LastWriteTiming:
    """Per-call timing for the last write executed in this asyncio Task.

    Read via ``last_write_timing()`` after awaiting ``execute()``. Surfaced as
    response headers by the ingest router so the engine can read the server's
    real queue/exec cost on every request.
    """

    label: str
    queue_wait_ms: float
    exec_ms: float


_last_write_timing: contextvars.ContextVar[LastWriteTiming | None] = contextvars.ContextVar(
    "longhouse_write_serializer_last_timing",
    default=None,
)


def last_write_timing() -> LastWriteTiming | None:
    """Return the timing of the most recent write in this asyncio context."""
    return _last_write_timing.get()


class WriteQueueTimeoutError(TimeoutError):
    """Raised when a write waits too long for the serializer slot."""

    def __init__(self, *, label: str, queue_timeout_seconds: float) -> None:
        self.label = label
        self.queue_timeout_seconds = queue_timeout_seconds
        super().__init__(f"WriteSerializer queue wait for {label or 'unlabeled'} exceeded {queue_timeout_seconds:.1f}s")


class InterruptedWriteError(RuntimeError):
    """Raised when the active SQLite writer is interrupted by the watchdog."""

    def __init__(self, *, label: str, interrupt_after_seconds: float) -> None:
        self.label = label
        self.interrupt_after_seconds = interrupt_after_seconds
        super().__init__(
            f"WriteSerializer write for {label or 'unlabeled'} exceeded " f"{interrupt_after_seconds:.1f}s and was interrupted"
        )


def request_session_released_by_serializer(ws: object) -> bool:
    """Return true when ``execute_after_closing_request_session`` closed fallback DB."""

    return bool(getattr(ws, "is_configured", False)) and os.getenv("TESTING", "").strip().lower() not in _TRUTHY_ENV


@contextmanager
def post_write_db_session(ws: object, fallback_db: Session) -> Iterator[Session]:
    """Yield a usable DB session after a request-session-releasing write."""

    if request_session_released_by_serializer(ws):
        from zerg.database import get_session_factory

        SessionLocal = get_session_factory()
        with SessionLocal() as db:
            yield db
        return
    yield fallback_db


def post_write_fallback_db(ws: object, fallback_db: Session) -> Session | None:
    """Return a safe fallback DB for deferred post-write helpers."""

    if request_session_released_by_serializer(ws):
        return None
    return fallback_db


async def execute_post_write(
    ws: object,
    fn: Callable[[Session], T],
    fallback_db: Session | None,
    *,
    label: str = "",
    priority: int | None = None,
    auto_commit: bool = True,
    timeout_seconds: float | None = None,
    queue_timeout_seconds: float | None = None,
) -> T:
    """Execute a follow-up write after a request-session-releasing write."""

    execute_or_direct = getattr(ws, "execute_or_direct")
    kwargs: dict[str, object] = {
        "label": label,
        "auto_commit": auto_commit,
    }
    if priority is not None:
        kwargs["priority"] = priority
    if timeout_seconds is not None:
        kwargs["timeout_seconds"] = timeout_seconds
    if queue_timeout_seconds is not None:
        kwargs["queue_timeout_seconds"] = queue_timeout_seconds
    if fallback_db is None:
        return await execute_or_direct(fn, None, **kwargs)
    with post_write_db_session(ws, fallback_db) as db:
        return await execute_or_direct(fn, db, **kwargs)


class WriteSerializer:
    """Serialize all SQLite writes through a single lock.

    Ensures only one write transaction runs at a time, eliminating
    'database is locked' errors from concurrent background writers.
    """

    def __init__(self) -> None:
        self._wait_cond = asyncio.Condition()
        self._session_factory: sessionmaker | None = None
        self._session_factory_resolver: Callable[[], sessionmaker] | None = None
        self._stats = WriteStats()
        self._configured = False
        self._queue: list[_QueuedWrite] = []
        self._next_seq = 0
        self._writer_active = False
        self._active_label: str | None = None
        self._active_priority: int | None = None
        self._active_job_id: int | None = None
        self._active_worker_thread_id: int | None = None
        self._active_sqlite_connection: sqlite3.Connection | None = None
        self._active_interrupt_requested = False
        self._active_interrupt_after_seconds: float | None = None
        self._active_stage: str | None = None
        self._active_started_at: float | None = None
        self._active_stack_dump_count = 0
        self._active_interrupt_count = 0
        self._active_wedged_writer_count = 0
        self._fairness_promotions = 0
        self._last_active_interrupt_at_iso: str | None = None
        self._last_active_interrupt_age_ms: float | None = None
        self._last_active_interrupt_label: str | None = None
        self._last_active_wedged_writer_at_iso: str | None = None
        self._last_active_wedged_writer_age_ms: float | None = None
        self._last_active_wedged_writer_label: str | None = None
        self._last_active_wedged_writer_reason: str | None = None
        self._last_active_stack_dump_at: float | None = None
        self._last_active_stack_dump_iso: str | None = None
        self._last_active_stack_dump_age_ms: float | None = None
        self._last_active_stack_dump_reason: str | None = None
        self._last_active_stack_dump_text: str | None = None
        self._background_tasks: set[asyncio.Task[None]] = set()
        self._change_event = asyncio.Event()
        self._change_seq = 0

    def configure(self, session_factory: sessionmaker) -> None:
        """Set the write session factory. Call once at startup."""
        self._session_factory = session_factory
        self._session_factory_resolver = None
        self._configured = True
        _last_write_timing.set(None)
        logger.info("WriteSerializer configured")

    def configure_resolver(self, session_factory_resolver: Callable[[], sessionmaker]) -> None:
        """Set a dynamic session-factory resolver.

        This allows test/E2E routing to choose the correct SQLite file per
        request while keeping the serializer abstraction intact.
        """
        self._session_factory = None
        self._session_factory_resolver = session_factory_resolver
        self._configured = True
        _last_write_timing.set(None)
        logger.info("WriteSerializer configured")

    @property
    def is_configured(self) -> bool:
        return self._configured

    @property
    def stats(self) -> WriteStats:
        return self._stats

    @property
    def queue_depth(self) -> int:
        return len(self._queue)

    @property
    def writer_active(self) -> bool:
        return self._writer_active

    @property
    def active_label(self) -> str | None:
        return self._active_label

    @property
    def active_priority(self) -> int | None:
        return self._active_priority

    @property
    def active_job_id(self) -> int | None:
        return self._active_job_id

    @property
    def active_worker_thread_id(self) -> int | None:
        return self._active_worker_thread_id

    @property
    def active_stage(self) -> str | None:
        return self._active_stage

    def set_active_stage(self, stage: str | None) -> None:
        """Record the current coarse stage for health/debug metrics."""

        if stage is None:
            self._active_stage = None
            return
        cleaned = str(stage).strip()
        self._active_stage = cleaned or None

    @property
    def active_age_ms(self) -> float:
        if self._active_started_at is None:
            return 0.0
        return (time.monotonic() - self._active_started_at) * 1000

    async def repair_idle_queue(self) -> bool:
        """Promote a queued writer if the queue is nonempty but no writer owns the slot.

        Admission-control callers use this before treating queue depth as
        pressure. It closes the invariant gap where a cancelled or timed-out
        request can leave queued work visible even though the writer slot is
        idle.
        """
        async with self._wait_cond:
            if not self._queue or self._writer_active:
                return False
            self._promote_next_locked()
            self._wait_cond.notify_all()
            return self._writer_active

    def _promote_next_locked(self) -> None:
        if self._writer_active:
            return
        while self._queue:
            queued = self._pop_next_locked()
            if queued.ready.cancelled():
                continue
            self._writer_active = True
            self._active_label = queued.label
            self._active_priority = queued.priority
            self._active_job_id = queued.seq
            self._active_worker_thread_id = None
            self._active_sqlite_connection = None
            self._active_interrupt_requested = False
            self._active_interrupt_after_seconds = None
            self._active_started_at = time.monotonic()
            if not queued.ready.done():
                queued.ready.set_result(None)
            return

    def _pop_next_locked(self) -> _QueuedWrite:
        promote_after_ms = _env_float(
            "LONGHOUSE_WRITE_SERIALIZER_FAIRNESS_PROMOTE_AFTER_MS",
            _DEFAULT_FAIRNESS_PROMOTE_AFTER_MS,
        )
        if promote_after_ms > 0:
            now = time.monotonic()
            aged: list[tuple[float, int, int, int, _QueuedWrite]] = []
            for index, item in enumerate(self._queue):
                if item.ready.cancelled():
                    continue
                wait_ms = (now - item.enqueued_at) * 1000
                if wait_ms >= promote_after_ms:
                    aged.append((item.enqueued_at, item.priority, item.seq, index, item))
            if aged:
                _, _, _, index, queued = min(aged)
                self._queue.pop(index)
                heapq.heapify(self._queue)
                self._fairness_promotions += 1
                return queued
        return heapq.heappop(self._queue)

    def capture_active_worker_stack_if_stale(self, *, reason: str = "watchdog", force: bool = False) -> bool:
        """Log the active writer thread stack when it exceeds the evidence threshold."""

        if not self._writer_active:
            return False
        active_age_ms = self.active_age_ms
        threshold_ms = _env_float("LONGHOUSE_WRITE_SERIALIZER_STACK_DUMP_AFTER_MS", _DEFAULT_STACK_DUMP_AFTER_MS)
        if not force and active_age_ms < threshold_ms:
            return False

        now = time.monotonic()
        rate_limit_ms = _env_float(
            "LONGHOUSE_WRITE_SERIALIZER_STACK_DUMP_RATE_LIMIT_MS",
            _DEFAULT_STACK_DUMP_RATE_LIMIT_MS,
        )
        if not force and self._last_active_stack_dump_at is not None and (now - self._last_active_stack_dump_at) * 1000 < rate_limit_ms:
            return False

        thread_id = self._active_worker_thread_id
        frame = sys._current_frames().get(thread_id) if thread_id is not None else None
        if frame is None:
            stack_text = "<active writer worker thread not yet visible>"
        else:
            stack_text = "".join(traceback.format_stack(frame, limit=80)).rstrip()

        self._active_stack_dump_count += 1
        self._last_active_stack_dump_at = now
        self._last_active_stack_dump_iso = _utc_now_iso()
        self._last_active_stack_dump_age_ms = active_age_ms
        self._last_active_stack_dump_reason = reason
        self._last_active_stack_dump_text = stack_text

        logger.warning(
            "WriteSerializer active writer stack dump reason=%s label=%s job_id=%s thread_id=%s " "age_ms=%.1f stage=%s\n%s",
            reason,
            self._active_label or "unlabeled",
            self._active_job_id,
            thread_id,
            active_age_ms,
            self._active_stage or "-",
            stack_text,
        )
        return True

    def _interrupt_after_seconds_for(self, *, timeout_seconds: float | None) -> float | None:
        configured = _env_float(
            "LONGHOUSE_WRITE_SERIALIZER_INTERRUPT_AFTER_SECONDS",
            _DEFAULT_INTERRUPT_AFTER_SECONDS,
        )
        if configured <= 0:
            return None
        if timeout_seconds is not None and timeout_seconds > 0 and configured >= timeout_seconds:
            grace_seconds = _env_float(
                "LONGHOUSE_WRITE_SERIALIZER_TIMEOUT_INTERRUPT_GRACE_SECONDS",
                _DEFAULT_TIMEOUT_INTERRUPT_GRACE_SECONDS,
            )
            return timeout_seconds + max(0.0, grace_seconds)
        return configured

    async def _interrupt_active_after(self, *, job_id: int, label: str, interrupt_after_seconds: float) -> None:
        try:
            await asyncio.sleep(interrupt_after_seconds)
            if not self._writer_active or self._active_job_id != job_id:
                return

            active_age_ms = self.active_age_ms
            self.capture_active_worker_stack_if_stale(reason="interrupt", force=True)
            self._active_interrupt_requested = True
            self._active_interrupt_after_seconds = interrupt_after_seconds
            self._active_interrupt_count += 1
            self._last_active_interrupt_at_iso = _utc_now_iso()
            self._last_active_interrupt_age_ms = active_age_ms
            self._last_active_interrupt_label = label

            conn = self._active_sqlite_connection
            if conn is None:
                logger.warning(
                    "WriteSerializer interrupt requested but no sqlite connection is visible " "label=%s job_id=%s age_ms=%.1f",
                    label or "unlabeled",
                    job_id,
                    active_age_ms,
                )
                return

            logger.warning(
                "WriteSerializer interrupting active sqlite writer label=%s job_id=%s age_ms=%.1f deadline_s=%.1f",
                label or "unlabeled",
                job_id,
                active_age_ms,
                interrupt_after_seconds,
            )
            conn.interrupt()
            await self._escalate_if_interrupt_did_not_unwind(
                job_id=job_id,
                label=label,
                interrupt_after_seconds=interrupt_after_seconds,
            )
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.warning("WriteSerializer interrupt watchdog failed for %s", label or "unlabeled", exc_info=True)

    async def _escalate_if_interrupt_did_not_unwind(
        self,
        *,
        job_id: int,
        label: str,
        interrupt_after_seconds: float,
    ) -> None:
        grace_seconds = _env_float(
            "LONGHOUSE_WRITE_SERIALIZER_INTERRUPT_GRACE_SECONDS",
            _DEFAULT_INTERRUPT_GRACE_SECONDS,
        )
        await asyncio.sleep(max(0.0, grace_seconds))
        if not self._writer_active or self._active_job_id != job_id:
            return

        self._mark_wedged_writer(
            job_id=job_id,
            label=label,
            reason="interrupt_wedged",
            detail=f"interrupt_after_s={interrupt_after_seconds:.1f} grace_s={grace_seconds:.1f}",
        )
        self._exit_if_wedged_writer_enabled()

    def _mark_wedged_writer(self, *, job_id: int, label: str, reason: str, detail: str) -> None:
        active_age_ms = self.active_age_ms
        self.capture_active_worker_stack_if_stale(reason=reason, force=True)
        self._active_wedged_writer_count += 1
        self._last_active_wedged_writer_at_iso = _utc_now_iso()
        self._last_active_wedged_writer_age_ms = active_age_ms
        self._last_active_wedged_writer_label = label
        self._last_active_wedged_writer_reason = reason
        logger.critical(
            "WriteSerializer active writer wedged reason=%s label=%s job_id=%s age_ms=%.1f %s",
            reason,
            label or "unlabeled",
            job_id,
            active_age_ms,
            detail,
        )

    def _exit_if_wedged_writer_enabled(self) -> None:
        if self._wedged_writer_exit_enabled():
            logger.critical("WriteSerializer forcing process exit after wedged active writer")
            os._exit(86)

    def _wedged_writer_exit_enabled(self) -> bool:
        default_exit = os.getenv("TESTING", "").strip().lower() not in _TRUTHY_ENV
        return _env_bool("LONGHOUSE_WRITE_SERIALIZER_EXIT_ON_WEDGED_WRITER", default_exit)

    async def execute(
        self,
        fn: Callable[[Session], T],
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
        timeout_seconds: float | None = None,
        queue_timeout_seconds: float | None = None,
    ) -> T:
        """Submit a write operation. Serialized via a single-writer priority queue.

        Args:
            fn: Function receiving a Session. Do reads + writes here.
            label: Optional label for logging/metrics.
            priority: Lower runs sooner once the current writer finishes.
            auto_commit: If True, commit after fn returns. Set False if fn
                         manages its own commits (e.g. chunked ingest).
            timeout_seconds: Wall-clock timeout for the writer-slot hold.
                             On timeout the caller gets TimeoutError but the
                             write continues to completion in the background.
                             Use only for idempotent/background maintenance
                             writes; retries may duplicate effects.

        Returns:
            Whatever fn returns.

        Raises:
            Whatever fn raises (after rollback).
            TimeoutError if timeout_seconds elapses before the write completes.
        """
        return await self._execute_queued(
            fn,
            label=label,
            priority=priority,
            auto_commit=auto_commit,
            timeout_seconds=timeout_seconds,
            queue_timeout_seconds=queue_timeout_seconds,
            session_factory=self._resolve_session_factory(),
        )

    async def execute_with_session_factory(
        self,
        session_factory: sessionmaker,
        fn: Callable[[Session], T],
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
        timeout_seconds: float | None = None,
        queue_timeout_seconds: float | None = None,
    ) -> T:
        """Submit a write operation using the provided session factory."""
        return await self._execute_queued(
            fn,
            label=label,
            priority=priority,
            auto_commit=auto_commit,
            timeout_seconds=timeout_seconds,
            queue_timeout_seconds=queue_timeout_seconds,
            session_factory=session_factory,
        )

    async def _execute_queued(
        self,
        fn: Callable[[Session], T],
        *,
        label: str,
        priority: int | None,
        auto_commit: bool,
        timeout_seconds: float | None,
        queue_timeout_seconds: float | None,
        session_factory: sessionmaker,
    ) -> T:
        if not self._configured:
            raise RuntimeError("WriteSerializer not configured — call configure() first")

        t0 = time.monotonic()
        queued = _QueuedWrite(
            priority=_priority_for_label(label) if priority is None else priority,
            seq=self._next_seq,
            label=label,
            enqueued_at=t0,
            ready=asyncio.get_running_loop().create_future(),
        )
        self._next_seq += 1

        async with self._wait_cond:
            heapq.heappush(self._queue, queued)
            self._promote_next_locked()

        try:
            if queue_timeout_seconds is None:
                await queued.ready
            else:
                await asyncio.wait_for(queued.ready, timeout=queue_timeout_seconds)
        except asyncio.TimeoutError as exc:
            async with self._wait_cond:
                if any(item.seq == queued.seq for item in self._queue):
                    self._queue = [item for item in self._queue if item.seq != queued.seq]
                    heapq.heapify(self._queue)
                    self._promote_next_locked()
                    self._wait_cond.notify_all()
            raise WriteQueueTimeoutError(
                label=label,
                queue_timeout_seconds=queue_timeout_seconds,
            ) from exc
        except BaseException:
            async with self._wait_cond:
                if any(item.seq == queued.seq for item in self._queue):
                    self._queue = [item for item in self._queue if item.seq != queued.seq]
                    heapq.heapify(self._queue)
                    self._promote_next_locked()
                    self._wait_cond.notify_all()
            raise

        t1 = time.monotonic()
        queue_wait_ms = (t1 - t0) * 1000

        worker_task: asyncio.Task[T] = asyncio.create_task(
            asyncio.to_thread(self._run_with_factory, session_factory, fn, auto_commit, label)
        )
        interrupt_after_seconds = self._interrupt_after_seconds_for(timeout_seconds=timeout_seconds)
        interrupt_task: asyncio.Task[None] | None = None
        if interrupt_after_seconds is not None:
            interrupt_task = asyncio.create_task(
                self._interrupt_active_after(
                    job_id=queued.seq,
                    label=label,
                    interrupt_after_seconds=interrupt_after_seconds,
                )
            )
        finalized = False

        async def _finalize(*, was_cancelled: bool) -> None:
            nonlocal finalized
            if finalized:
                return
            finalized = True

            exec_ms = (time.monotonic() - t1) * 1000
            worker_exc: BaseException | None = None
            if worker_task.done():
                try:
                    worker_exc = worker_task.exception()
                except asyncio.CancelledError as exc:  # pragma: no cover - defensive
                    worker_exc = exc

            self._stats.total_writes += 1
            self._stats.total_queue_wait_ms += queue_wait_ms
            self._stats.total_exec_ms += exec_ms
            self._stats.max_queue_wait_ms = max(self._stats.max_queue_wait_ms, queue_wait_ms)
            self._stats.max_exec_ms = max(self._stats.max_exec_ms, exec_ms)
            if label:
                self._stats._label_counts[label] = self._stats._label_counts.get(label, 0) + 1
            self._stats.record_sample(label, queue_wait_ms, exec_ms)
            if isinstance(worker_exc, Exception):
                self._stats.errors += 1
            # Phase 1 instrumentation: stash the timing for the calling Task so
            # the router can surface it as response headers.
            _last_write_timing.set(
                LastWriteTiming(
                    label=label,
                    queue_wait_ms=queue_wait_ms,
                    exec_ms=exec_ms,
                )
            )

            if queue_wait_ms > 500 or exec_ms > 1000:
                logger.warning(
                    "WriteSerializer: %s waited %.0fms in queue, exec %.0fms",
                    label or "unlabeled",
                    queue_wait_ms,
                    exec_ms,
                )

            if was_cancelled and worker_exc is not None:
                logger.warning(
                    "WriteSerializer: %s finished with %s after cancellation",
                    label or "unlabeled",
                    type(worker_exc).__name__,
                )

            async with self._wait_cond:
                if interrupt_task is not None and not interrupt_task.done():
                    interrupt_task.cancel()
                self._writer_active = False
                self._active_label = None
                self._active_priority = None
                self._active_job_id = None
                self._active_worker_thread_id = None
                self._active_sqlite_connection = None
                self._active_interrupt_requested = False
                self._active_interrupt_after_seconds = None
                self._active_stage = None
                self._active_started_at = None
                self._promote_next_locked()
                self._wait_cond.notify_all()

        def _schedule_background_finalize(done_task: asyncio.Task[T]) -> None:
            async def _runner() -> None:
                deadline_seconds = _env_float(
                    "LONGHOUSE_WRITE_SERIALIZER_BACKGROUND_FINALIZE_GRACE_SECONDS",
                    _DEFAULT_BACKGROUND_FINALIZE_GRACE_SECONDS,
                )
                if interrupt_after_seconds is not None:
                    deadline_seconds += interrupt_after_seconds
                elif timeout_seconds is not None and timeout_seconds > 0:
                    deadline_seconds += timeout_seconds

                timed_out = False
                try:
                    await asyncio.wait_for(asyncio.shield(done_task), timeout=max(0.0, deadline_seconds))
                except asyncio.TimeoutError:
                    timed_out = True
                except BaseException:
                    pass

                if timed_out and self._writer_active and self._active_job_id == queued.seq:
                    self._mark_wedged_writer(
                        job_id=queued.seq,
                        label=label,
                        reason="background_finalize_deadman",
                        detail=f"deadline_s={deadline_seconds:.1f}",
                    )
                    if self._wedged_writer_exit_enabled():
                        self._exit_if_wedged_writer_enabled()
                    else:
                        logger.critical(
                            "WriteSerializer releasing wedged writer slot with forced exit disabled; "
                            "stale worker thread may still be running label=%s job_id=%s",
                            label or "unlabeled",
                            queued.seq,
                        )
                await _finalize(was_cancelled=True)

            task = asyncio.create_task(_runner())
            self._background_tasks.add(task)
            task.add_done_callback(self._background_tasks.discard)

        try:
            if timeout_seconds is None:
                result = await asyncio.shield(worker_task)
            else:
                result = await asyncio.wait_for(asyncio.shield(worker_task), timeout=timeout_seconds)
        except asyncio.TimeoutError:
            logger.warning(
                "WriteSerializer: %s timed out after %.1fs, continuing in background",
                label or "unlabeled",
                timeout_seconds,
            )
            _schedule_background_finalize(worker_task)
            raise
        except asyncio.CancelledError:
            _schedule_background_finalize(worker_task)
            raise
        except BaseException:
            await _finalize(was_cancelled=False)
            raise

        await _finalize(was_cancelled=False)
        self._notify_change()
        return result

    def _notify_change(self) -> None:
        """Signal that a write completed. Wakes any waiting SSE loops."""
        self._change_seq += 1
        self._change_event.set()
        self._change_event = asyncio.Event()

    @property
    def change_seq(self) -> int:
        """Monotonic counter incremented after every successful write."""
        return self._change_seq

    async def wait_for_change(self, timeout: float = 5.0) -> bool:
        """Wait up to *timeout* seconds for the next write to complete.

        Returns True if a change was signalled, False on timeout.
        SSE loops use this instead of blind ``asyncio.sleep(1)``.
        """
        evt = self._change_event
        try:
            await asyncio.wait_for(evt.wait(), timeout=timeout)
            return True
        except asyncio.TimeoutError:
            return False

    async def execute_or_direct(
        self,
        fn: Callable[[Session], T],
        fallback_db: Session | None = None,
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
        timeout_seconds: float | None = None,
        queue_timeout_seconds: float | None = None,
    ) -> T:
        """Execute via serializer if configured, otherwise run directly on fallback_db.

        This eliminates the need for if/else blocks at every callsite.
        """
        if self._configured and fallback_db is not None and os.getenv("TESTING", "").strip().lower() in _TRUTHY_ENV:
            # Unit tests frequently override request DB dependencies to point at
            # per-test SQLite files. Once the app startup configures the global
            # serializer, routing those writes through the process-wide factory
            # hits the wrong database and breaks request-scoped assertions.
            return self._run_inline_with_timing(fn, fallback_db, auto_commit, label)
        if self._configured:
            return await self.execute(
                fn,
                label=label,
                priority=priority,
                auto_commit=auto_commit,
                timeout_seconds=timeout_seconds,
                queue_timeout_seconds=queue_timeout_seconds,
            )
        if fallback_db is None:
            raise RuntimeError("WriteSerializer not configured and no fallback_db provided")
        return self._run_inline_with_timing(fn, fallback_db, auto_commit, label)

    async def execute_after_closing_request_session(
        self,
        fn: Callable[[Session], T],
        fallback_db: Session,
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
        timeout_seconds: float | None = None,
        queue_timeout_seconds: float | None = None,
    ) -> T:
        """Execute a serialized write without holding a request DB checkout.

        Use this only after the caller has copied all values it needs from the
        request-scoped Session and will not touch that Session again. In tests,
        request DB overrides still run inline through ``fallback_db`` so focused
        route tests keep using their per-test SQLite database.
        """
        if self._configured and os.getenv("TESTING", "").strip().lower() not in _TRUTHY_ENV:
            fallback_db.close()
            return await self.execute(
                fn,
                label=label,
                priority=priority,
                auto_commit=auto_commit,
                timeout_seconds=timeout_seconds,
                queue_timeout_seconds=queue_timeout_seconds,
            )
        return await self.execute_or_direct(
            fn,
            fallback_db,
            label=label,
            priority=priority,
            auto_commit=auto_commit,
            timeout_seconds=timeout_seconds,
            queue_timeout_seconds=queue_timeout_seconds,
        )

    def _run_inline_with_timing(
        self,
        fn: Callable[[Session], T],
        db: Session,
        auto_commit: bool,
        label: str,
    ) -> T:
        """Inline-execute fn, still recording timing on the contextvar so
        callers (the ingest router) can surface uniform headers."""
        t0 = time.monotonic()
        result = fn(db)
        if auto_commit:
            db.commit()
        exec_ms = (time.monotonic() - t0) * 1000
        _last_write_timing.set(LastWriteTiming(label=label, queue_wait_ms=0.0, exec_ms=exec_ms))
        self._stats.record_sample(label, 0.0, exec_ms)
        return result

    def execute_sync(
        self,
        fn: Callable[[Session], T],
        *,
        label: str = "",
        auto_commit: bool = True,
    ) -> T:
        """Synchronous write for non-async contexts (startup, migrations).

        NOT serialized with async writes — only use during startup before
        the event loop is serving requests.
        """
        if not self._configured:
            raise RuntimeError("WriteSerializer not configured — call configure() first")
        return self._run(fn, auto_commit, label)

    def _run(self, fn: Callable[[Session], T], auto_commit: bool, label: str) -> T:
        """Execute fn with a fresh session. Runs in a worker thread."""
        return self._run_with_factory(self._resolve_session_factory(), fn, auto_commit, label)

    def _run_with_factory(
        self,
        session_factory: sessionmaker,
        fn: Callable[[Session], T],
        auto_commit: bool,
        label: str,
    ) -> T:
        """Execute fn with a fresh session from the provided factory."""
        db = session_factory()
        self._active_worker_thread_id = threading.get_ident()
        self._active_sqlite_connection = _sqlite_connection_from_session(db)
        try:
            result = fn(db)
            if auto_commit:
                db.commit()
            return result
        except Exception as exc:
            db.rollback()
            if label:
                logger.debug("WriteSerializer: %s rolled back", label)
            if self._active_interrupt_requested and _looks_like_sqlite_interrupt(exc):
                raise InterruptedWriteError(
                    label=label,
                    interrupt_after_seconds=self._active_interrupt_after_seconds or 0.0,
                ) from exc
            raise
        finally:
            db.close()

    def _resolve_session_factory(self) -> sessionmaker:
        if self._session_factory_resolver is not None:
            return self._session_factory_resolver()
        if self._session_factory is None:
            raise RuntimeError("WriteSerializer session factory not configured")
        return self._session_factory

    def get_metrics(self) -> dict[str, Any]:
        """Return serializer metrics for health/debug endpoints."""
        self.capture_active_worker_stack_if_stale(reason="metrics")
        s = self._stats
        avg_wait = s.total_queue_wait_ms / s.total_writes if s.total_writes else 0
        avg_exec = s.total_exec_ms / s.total_writes if s.total_writes else 0
        # Rolling per-label percentiles over the last _HISTOGRAM_WINDOW samples.
        # The engine's adaptive controller (phase 2) consumes these via /api/health.
        rolling: dict[str, dict[str, Any]] = {}
        for key, hist in s._label_histograms.items():
            rolling[key] = {
                "queue_wait_ms": _percentiles(hist.queue_wait_ms),
                "exec_ms": _percentiles(hist.exec_ms),
            }
        return {
            "writer_active": self._writer_active,
            "active_label": self._active_label,
            "active_priority": self._active_priority,
            "active_job_id": self._active_job_id,
            "active_worker_thread_id": self._active_worker_thread_id,
            "active_interrupt_after_seconds": self._active_interrupt_after_seconds,
            "active_stage": self._active_stage,
            "active_age_ms": round(self.active_age_ms, 1),
            "queue_depth": len(self._queue),
            "idle_queue_stalled": bool(self._queue and not self._writer_active),
            "queued_labels": [item.label for item in sorted(self._queue)[:5]],
            "total_writes": s.total_writes,
            "errors": s.errors,
            "fairness_promotions": self._fairness_promotions,
            "avg_queue_wait_ms": round(avg_wait, 1),
            "max_queue_wait_ms": round(s.max_queue_wait_ms, 1),
            "avg_exec_ms": round(avg_exec, 1),
            "max_exec_ms": round(s.max_exec_ms, 1),
            "label_counts": dict(s._label_counts),
            "rolling_window": _HISTOGRAM_WINDOW,
            "rolling_by_label": rolling,
            "active_stack_dump_count": self._active_stack_dump_count,
            "active_interrupt_count": self._active_interrupt_count,
            "active_wedged_writer_count": self._active_wedged_writer_count,
            "last_active_interrupt_at": self._last_active_interrupt_at_iso,
            "last_active_interrupt_age_ms": (
                round(self._last_active_interrupt_age_ms, 1) if self._last_active_interrupt_age_ms is not None else None
            ),
            "last_active_interrupt_label": self._last_active_interrupt_label,
            "last_active_wedged_writer_at": self._last_active_wedged_writer_at_iso,
            "last_active_wedged_writer_age_ms": (
                round(self._last_active_wedged_writer_age_ms, 1) if self._last_active_wedged_writer_age_ms is not None else None
            ),
            "last_active_wedged_writer_label": self._last_active_wedged_writer_label,
            "last_active_wedged_writer_reason": self._last_active_wedged_writer_reason,
            "last_active_stack_dump_at": self._last_active_stack_dump_iso,
            "last_active_stack_dump_age_ms": (
                round(self._last_active_stack_dump_age_ms, 1) if self._last_active_stack_dump_age_ms is not None else None
            ),
            "last_active_stack_dump_reason": self._last_active_stack_dump_reason,
        }


# Process singletons. The live serializer is intentionally separate from the
# archive serializer so hot writes do not queue behind archive work.
_serializer = WriteSerializer()
_live_serializer = WriteSerializer()


def get_write_serializer() -> WriteSerializer:
    return _serializer


def get_live_write_serializer() -> WriteSerializer:
    return _live_serializer
