"""Single-writer serializer for SQLite.

SQLite permits only one writer at a time. When multiple background tasks
(ingest, presence flush, task queue, commis jobs) all compete for the write
lock via separate threads, `database is locked` errors and long waits result.

This module serializes ALL database writes through a single asyncio.Lock.
While one write executes, others wait in the queue. Reads are unaffected
(WAL mode allows unlimited concurrent readers).

Usage:
    from zerg.services.write_serializer import write_serializer

    # In async context:
    result = await write_serializer.execute(lambda db: do_writes(db))

    # With priority (lower = higher priority):
    await write_serializer.execute(fn, label="presence-flush")

Architecture:
    - A priority queue ensures one write at a time while letting
      interactive auth/ingest writes cut ahead of maintenance work
    - Each write runs in asyncio.to_thread() to avoid blocking the event loop
    - The write function receives a fresh Session, does its work, and returns
    - Session lifecycle (commit on success, rollback on error, close) is managed
      by the serializer
    - A dedicated single-connection write engine prevents pool contention
"""

from __future__ import annotations

import asyncio
import heapq
import logging
import os
import time
from dataclasses import dataclass
from dataclasses import field
from typing import Any
from typing import Callable
from typing import TypeVar

from sqlalchemy.orm import Session
from sqlalchemy.orm import sessionmaker

logger = logging.getLogger(__name__)

T = TypeVar("T")
_MISSING = object()
_TRUTHY_ENV = {"1", "true", "yes", "on"}

_DEFAULT_PRIORITY = 50
_LABEL_PRIORITIES: dict[str, int] = {
    # Interactive auth / token lifecycle should cut ahead of background churn.
    "refresh-session": 0,
    "device-token-create": 0,
    "device-token-revoke": 0,
    # Managed runtime events are the live UI truth lane and should cut ahead of
    # hook presence chatter when the machine is busy.
    "runtime-events": 5,
    # Live transcript deltas are user-visible and can be regenerated by the
    # archive lane, so keep them ahead of durable background ingest.
    "ingest-live": 6,
    # Transcript ingest is durable archive truth. It can trail runtime events,
    # but it should not sit behind high-volume presence retries.
    "runtime-observations": 5,
    "ingest": 10,
    # Daemon archive repair is intentionally behind health/control signals. It
    # can be regenerated from local files and should not make the machine look
    # offline while an old backlog drains.
    "ingest-scan": 45,
    "ingest-replay": 45,
    "runner-online": 10,
    "session-turn-active": 15,
    "session-turn-terminal": 15,
    "presence": 20,
    "presence-flush": 20,
    "runner-output": 20,
    "runner-job-complete": 20,
    "runner-job-error": 20,
    "runner-offline": 20,
    "loop-thread": 25,
    "loop-thread-message": 25,
    "turn-review-create": 30,
    "turn-review-complete": 30,
    "turn-review-existing": 30,
    "wakeup-ledger": 35,
    "heartbeat": 40,
    # Summary task bookkeeping and the final summary row update are small and
    # user-visible. Keep them ahead of archive ingest so a busy ingest storm
    # cannot pin the cold worker in "running" after a timeout.
    "summary": 7,
    "summary-title": 7,
    "task-claim": 7,
    "task-done": 7,
    "task-retry": 7,
    "task-continue": 7,
    "task-timeout": 7,
    "task-fail": 7,
    "summary-backfill": 60,
    "embeddings": 60,
    # Background queue maintenance is lowest priority.
    "task-resurrect": 85,
    "commis-claim": 85,
    "commis-reclaim": 85,
    "commis-reclaim-async": 85,
    "commis-heartbeat": 85,
    "job-run": 90,
}


def _priority_for_label(label: str) -> int:
    normalized = (label or "").strip().lower()
    return _LABEL_PRIORITIES.get(normalized, _DEFAULT_PRIORITY)


@dataclass(order=True)
class _QueuedWrite:
    priority: int
    seq: int
    label: str = field(compare=False, default="")


@dataclass
class WriteStats:
    """Cumulative write serializer statistics."""

    total_writes: int = 0
    total_queue_wait_ms: float = 0
    total_exec_ms: float = 0
    max_queue_wait_ms: float = 0
    max_exec_ms: float = 0
    errors: int = 0
    _label_counts: dict[str, int] = field(default_factory=dict)


class WriteSerializer:
    """Serialize all SQLite writes through a single lock.

    Ensures only one write transaction runs at a time, eliminating
    'database is locked' errors from concurrent background writers.
    """

    def __init__(self) -> None:
        self._wait_cond = asyncio.Condition()
        self._session_factory: sessionmaker | None = None
        self._session_factory_resolver: Callable[[], sessionmaker] | None = None
        self._stats = WriteStats()
        self._configured = False
        self._queue: list[_QueuedWrite] = []
        self._next_seq = 0
        self._writer_active = False
        self._background_tasks: set[asyncio.Task[None]] = set()
        self._change_event = asyncio.Event()
        self._change_seq = 0

    def configure(self, session_factory: sessionmaker) -> None:
        """Set the write session factory. Call once at startup."""
        self._session_factory = session_factory
        self._session_factory_resolver = None
        self._configured = True
        logger.info("WriteSerializer configured")

    def configure_resolver(self, session_factory_resolver: Callable[[], sessionmaker]) -> None:
        """Set a dynamic session-factory resolver.

        This allows test/E2E routing to choose the correct SQLite file per
        request while keeping the serializer abstraction intact.
        """
        self._session_factory = None
        self._session_factory_resolver = session_factory_resolver
        self._configured = True
        logger.info("WriteSerializer configured")

    @property
    def is_configured(self) -> bool:
        return self._configured

    @property
    def stats(self) -> WriteStats:
        return self._stats

    async def execute(
        self,
        fn: Callable[[Session], T],
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
    ) -> T:
        """Submit a write operation. Serialized via a single-writer priority queue.

        Args:
            fn: Function receiving a Session. Do reads + writes here.
            label: Optional label for logging/metrics.
            priority: Lower runs sooner once the current writer finishes.
            auto_commit: If True, commit after fn returns. Set False if fn
                         manages its own commits (e.g. chunked ingest).

        Returns:
            Whatever fn returns.

        Raises:
            Whatever fn raises (after rollback).
        """
        return await self._execute_queued(
            fn,
            label=label,
            priority=priority,
            auto_commit=auto_commit,
            session_factory=self._resolve_session_factory(),
        )

    async def execute_with_session_factory(
        self,
        session_factory: sessionmaker,
        fn: Callable[[Session], T],
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
    ) -> T:
        """Submit a write operation using the provided session factory."""
        return await self._execute_queued(
            fn,
            label=label,
            priority=priority,
            auto_commit=auto_commit,
            session_factory=session_factory,
        )

    async def _execute_queued(
        self,
        fn: Callable[[Session], T],
        *,
        label: str,
        priority: int | None,
        auto_commit: bool,
        session_factory: sessionmaker,
    ) -> T:
        if not self._configured:
            raise RuntimeError("WriteSerializer not configured — call configure() first")

        t0 = time.monotonic()
        queued = _QueuedWrite(
            priority=_priority_for_label(label) if priority is None else priority,
            seq=self._next_seq,
            label=label,
        )
        self._next_seq += 1

        async with self._wait_cond:
            heapq.heappush(self._queue, queued)
            try:
                while True:
                    head = self._queue[0]
                    if not self._writer_active and head.seq == queued.seq:
                        heapq.heappop(self._queue)
                        self._writer_active = True
                        break
                    await self._wait_cond.wait()
            except BaseException:
                if any(item.seq == queued.seq for item in self._queue):
                    self._queue = [item for item in self._queue if item.seq != queued.seq]
                    heapq.heapify(self._queue)
                    self._wait_cond.notify_all()
                raise

        t1 = time.monotonic()
        queue_wait_ms = (t1 - t0) * 1000

        worker_task: asyncio.Task[T] = asyncio.create_task(
            asyncio.to_thread(self._run_with_factory, session_factory, fn, auto_commit, label)
        )
        finalized = False

        async def _finalize(*, was_cancelled: bool) -> None:
            nonlocal finalized
            if finalized:
                return
            finalized = True

            exec_ms = (time.monotonic() - t1) * 1000
            worker_exc: BaseException | None = None
            if worker_task.done():
                try:
                    worker_exc = worker_task.exception()
                except asyncio.CancelledError as exc:  # pragma: no cover - defensive
                    worker_exc = exc

            self._stats.total_writes += 1
            self._stats.total_queue_wait_ms += queue_wait_ms
            self._stats.total_exec_ms += exec_ms
            self._stats.max_queue_wait_ms = max(self._stats.max_queue_wait_ms, queue_wait_ms)
            self._stats.max_exec_ms = max(self._stats.max_exec_ms, exec_ms)
            if label:
                self._stats._label_counts[label] = self._stats._label_counts.get(label, 0) + 1
            if isinstance(worker_exc, Exception):
                self._stats.errors += 1

            if queue_wait_ms > 500 or exec_ms > 1000:
                logger.warning(
                    "WriteSerializer: %s waited %.0fms in queue, exec %.0fms",
                    label or "unlabeled",
                    queue_wait_ms,
                    exec_ms,
                )

            if was_cancelled and worker_exc is not None:
                logger.warning(
                    "WriteSerializer: %s finished with %s after cancellation",
                    label or "unlabeled",
                    type(worker_exc).__name__,
                )

            async with self._wait_cond:
                self._writer_active = False
                self._wait_cond.notify_all()

        def _schedule_background_finalize(done_task: asyncio.Task[T]) -> None:
            async def _runner() -> None:
                try:
                    await asyncio.shield(done_task)
                except BaseException:
                    pass
                await _finalize(was_cancelled=True)

            task = asyncio.create_task(_runner())
            self._background_tasks.add(task)
            task.add_done_callback(self._background_tasks.discard)

        try:
            result = await asyncio.shield(worker_task)
        except asyncio.CancelledError:
            worker_task.add_done_callback(_schedule_background_finalize)
            raise
        except BaseException:
            await _finalize(was_cancelled=False)
            raise

        await _finalize(was_cancelled=False)
        self._notify_change()
        return result

    def _notify_change(self) -> None:
        """Signal that a write completed. Wakes any waiting SSE loops."""
        self._change_seq += 1
        self._change_event.set()
        self._change_event = asyncio.Event()

    @property
    def change_seq(self) -> int:
        """Monotonic counter incremented after every successful write."""
        return self._change_seq

    async def wait_for_change(self, timeout: float = 5.0) -> bool:
        """Wait up to *timeout* seconds for the next write to complete.

        Returns True if a change was signalled, False on timeout.
        SSE loops use this instead of blind ``asyncio.sleep(1)``.
        """
        evt = self._change_event
        try:
            await asyncio.wait_for(evt.wait(), timeout=timeout)
            return True
        except asyncio.TimeoutError:
            return False

    async def execute_or_direct(
        self,
        fn: Callable[[Session], T],
        fallback_db: Session | None = None,
        *,
        label: str = "",
        priority: int | None = None,
        auto_commit: bool = True,
    ) -> T:
        """Execute via serializer if configured, otherwise run directly on fallback_db.

        This eliminates the need for if/else blocks at every callsite.
        """
        if self._configured and fallback_db is not None and os.getenv("TESTING", "").strip().lower() in _TRUTHY_ENV:
            # Unit tests frequently override request DB dependencies to point at
            # per-test SQLite files. Once the app startup configures the global
            # serializer, routing those writes through the process-wide factory
            # hits the wrong database and breaks request-scoped assertions.
            result = fn(fallback_db)
            if auto_commit:
                fallback_db.commit()
            return result
        if self._configured:
            return await self.execute(fn, label=label, priority=priority, auto_commit=auto_commit)
        if fallback_db is None:
            raise RuntimeError("WriteSerializer not configured and no fallback_db provided")
        result = fn(fallback_db)
        if auto_commit:
            fallback_db.commit()
        return result

    def execute_sync(
        self,
        fn: Callable[[Session], T],
        *,
        label: str = "",
        auto_commit: bool = True,
    ) -> T:
        """Synchronous write for non-async contexts (startup, migrations).

        NOT serialized with async writes — only use during startup before
        the event loop is serving requests.
        """
        if not self._configured:
            raise RuntimeError("WriteSerializer not configured — call configure() first")
        return self._run(fn, auto_commit, label)

    def _run(self, fn: Callable[[Session], T], auto_commit: bool, label: str) -> T:
        """Execute fn with a fresh session. Runs in a worker thread."""
        return self._run_with_factory(self._resolve_session_factory(), fn, auto_commit, label)

    def _run_with_factory(
        self,
        session_factory: sessionmaker,
        fn: Callable[[Session], T],
        auto_commit: bool,
        label: str,
    ) -> T:
        """Execute fn with a fresh session from the provided factory."""
        db = session_factory()
        try:
            result = fn(db)
            if auto_commit:
                db.commit()
            return result
        except Exception:
            db.rollback()
            if label:
                logger.debug("WriteSerializer: %s rolled back", label)
            raise
        finally:
            db.close()

    def _resolve_session_factory(self) -> sessionmaker:
        if self._session_factory_resolver is not None:
            return self._session_factory_resolver()
        if self._session_factory is None:
            raise RuntimeError("WriteSerializer session factory not configured")
        return self._session_factory

    def get_metrics(self) -> dict[str, Any]:
        """Return serializer metrics for health/debug endpoints."""
        s = self._stats
        avg_wait = s.total_queue_wait_ms / s.total_writes if s.total_writes else 0
        avg_exec = s.total_exec_ms / s.total_writes if s.total_writes else 0
        return {
            "total_writes": s.total_writes,
            "errors": s.errors,
            "avg_queue_wait_ms": round(avg_wait, 1),
            "max_queue_wait_ms": round(s.max_queue_wait_ms, 1),
            "avg_exec_ms": round(avg_exec, 1),
            "max_exec_ms": round(s.max_exec_ms, 1),
            "label_counts": dict(s._label_counts),
        }


# Process singleton
_serializer = WriteSerializer()


def get_write_serializer() -> WriteSerializer:
    return _serializer
