import type { DemoRecipe } from "./types";

export const DEMO_RECIPES: readonly DemoRecipe[] = [
  {
    id: "inventory-boundary",
    shortLabel: "Fix inventory count",
    prompt: "Fix the off-by-one bug in count_items in inventory.py, then run the tests.",
    file: "inventory.py",
    diagnosis: [
      "The loop skips the first shelf. I'll include every shelf and verify it.",
      "count_items starts at the second shelf. I'll correct the range and test it.",
    ],
    readOutput: "10  for shelf in shelves[1:]:",
    before: "for shelf in shelves[1:]:",
    after: "for shelf in shelves:",
    line: 10,
    testCommand: "python3 test_inventory.py",
    testOutput: "8 tests passed",
    summary: "The inventory count now includes every shelf. All tests pass.",
  },
  {
    id: "unknown-session-state",
    shortLabel: "Preserve unknown state",
    prompt: "Stop missing heartbeats from being shown as idle in session_state.py and run its tests.",
    file: "session_state.py",
    diagnosis: [
      "Missing evidence is being collapsed into idle. I'll preserve it as unknown.",
      "The fallback invents an idle state when no heartbeat exists. I'll make that explicit.",
    ],
    readOutput: "42  if last_seen is None: return 'idle'",
    before: "return 'idle'",
    after: "return 'unknown'",
    line: 42,
    testCommand: "python3 -m pytest tests/test_session_state.py -q",
    testOutput: "12 passed in 0.18s",
    summary: "Missing heartbeat evidence now stays unknown instead of appearing idle.",
  },
  {
    id: "blank-transcript-line",
    shortLabel: "Ignore blank transcript lines",
    prompt: "Fix the transcript parser so whitespace-only lines are ignored, then run parser tests.",
    file: "transcript.py",
    diagnosis: [
      "Whitespace-only input survives the current truthiness check. I'll normalize it first.",
      "The parser treats spaces as content. I'll strip before deciding whether to emit a row.",
    ],
    readOutput: "67  if line: events.append(parse(line))",
    before: "if line:",
    after: "if line.strip():",
    line: 67,
    testCommand: "python3 -m pytest tests/test_transcript.py -q",
    testOutput: "15 passed in 0.22s",
    summary: "Whitespace-only transcript lines are ignored and parser tests pass.",
  },
  {
    id: "retry-backoff",
    shortLabel: "Repair retry backoff",
    prompt: "Fix the retry backoff calculation in retry.py and make the failing test pass.",
    file: "retry.py",
    diagnosis: [
      "The delay grows linearly, but the contract requires exponential backoff. I'll fix it.",
      "The retry schedule uses multiplication by attempt instead of an exponent. I'll correct it.",
    ],
    readOutput: "31  delay = base * attempt",
    before: "delay = base * attempt",
    after: "delay = base * (2 ** attempt)",
    line: 31,
    testCommand: "python3 -m pytest tests/test_retry.py -q",
    precheckFailure: "FAILED test_backoff_schedule: expected 8, got 6",
    testOutput: "6 passed in 0.14s",
    summary: "Retry delays now follow the exponential schedule and the suite passes.",
  },
  {
    id: "config-precedence",
    shortLabel: "Fix config precedence",
    prompt: "Make environment values override defaults in config.py, then run the config tests.",
    file: "config.py",
    diagnosis: [
      "Defaults are checked before the environment. I'll reverse the precedence.",
      "The lookup returns the default too early. I'll let an environment value win.",
    ],
    readOutput: "24  return defaults.get(key) or env.get(key)",
    before: "return defaults.get(key) or env.get(key)",
    after: "return env.get(key, defaults.get(key))",
    line: 24,
    testCommand: "python3 -m pytest tests/test_config.py -q",
    testOutput: "9 passed in 0.11s",
    summary: "Environment values now override defaults and all config tests pass.",
  },
  {
    id: "scoped-cache-key",
    shortLabel: "Scope cache entries",
    prompt: "Include the project id in cache keys in cache.py and verify the cache tests.",
    file: "cache.py",
    diagnosis: [
      "Two projects can currently share the same cache key. I'll include the project scope.",
      "The key omits project identity, which leaks stale values across repositories. I'll scope it.",
    ],
    readOutput: "18  key = f'{provider}:{session_id}'",
    before: "key = f'{provider}:{session_id}'",
    after: "key = f'{project_id}:{provider}:{session_id}'",
    line: 18,
    testCommand: "python3 -m pytest tests/test_cache.py -q",
    testOutput: "11 passed in 0.16s",
    summary: "Cache entries are now isolated by project and the cache suite passes.",
  },
  {
    id: "safe-cli-default",
    shortLabel: "Correct CLI default",
    prompt: "Make --prune opt-in instead of enabled by default in cli.py and run CLI tests.",
    file: "cli.py",
    diagnosis: [
      "The destructive option is enabled by default. I'll make users opt in explicitly.",
      "The parser default contradicts the help text. I'll switch prune to an explicit flag.",
    ],
    readOutput: "53  parser.add_argument('--prune', default=True)",
    before: "parser.add_argument('--prune', default=True)",
    after: "parser.add_argument('--prune', action='store_true')",
    line: 53,
    testCommand: "python3 -m pytest tests/test_cli.py -q",
    testOutput: "10 passed in 0.19s",
    summary: "Pruning is now opt-in and the CLI behavior is covered by passing tests.",
  },
] as const;
