from sqlalchemy import JSON

# SQLAlchemy core imports
from sqlalchemy import Boolean
from sqlalchemy import Column
from sqlalchemy import Date
from sqlalchemy import DateTime
from sqlalchemy import ForeignKey
from sqlalchemy import Index
from sqlalchemy import Integer
from sqlalchemy import LargeBinary
from sqlalchemy import String
from sqlalchemy import Text
from sqlalchemy import UniqueConstraint
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.ext.mutable import MutableList
from sqlalchemy.orm import backref
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

# Local helpers / enums
from zerg.database import Base

from .user import User  # noqa: E402, F401

# ---------------------------------------------------------------------------
# AccountConnectorCredential – account-level credentials for built-in tools
# ---------------------------------------------------------------------------


class AccountConnectorCredential(Base):
    """Account-level encrypted credential for built-in connector tools.

    These credentials are shared across all tools owned by the user.

    The organization_id column is nullable and reserved for future
    multi-tenant support. When populated, credentials can be shared
    across an organization and agents reference organization_id for
    credential resolution.
    """

    __tablename__ = "account_connector_credentials"
    __table_args__ = (
        # One credential per connector type per owner
        UniqueConstraint("owner_id", "connector_type", name="uix_account_owner_connector"),
    )

    id = Column(Integer, primary_key=True, index=True)

    # Owner – the user who owns this credential
    owner_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Reserved for future organization/team support
    # When populated, enforces (organization_id, connector_type) uniqueness
    organization_id = Column(Integer, nullable=True, index=True)

    # Connector type identifier: 'slack', 'discord', 'email', 'sms',
    # 'github', 'jira', 'linear', 'notion', 'imessage'
    connector_type = Column(String(50), nullable=False)

    # Encrypted credential value (Fernet AES-GCM).
    # Fernet token string generated by the connector credential helpers.
    encrypted_value = Column(Text, nullable=False)

    # Optional user-friendly label (e.g., "Engineering Slack workspace")
    display_name = Column(String(255), nullable=True)

    # Metadata discovered during test (e.g., GitHub username, Slack workspace).
    # Stored as JSON, NOT encrypted (no secrets here).
    connector_metadata = Column(MutableDict.as_mutable(JSON), nullable=True)

    # Test status tracking
    test_status = Column(String(20), nullable=False, default="untested")
    last_tested_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    owner = relationship("User", backref="account_connector_credentials")


# ---------------------------------------------------------------------------
# Runners – User-owned execution infrastructure (Runners v1)
# ---------------------------------------------------------------------------


class Runner(Base):
    """User-owned runner daemon for executing commands.

    Runners connect outbound to the Longhouse platform and execute jobs
    on behalf of the user. This enables secure execution without backend
    access to user SSH keys.
    """

    __tablename__ = "runners"
    __table_args__ = (
        # Ensure unique runner names per owner
        UniqueConstraint("owner_id", "name", name="uix_runner_owner_name"),
    )

    id = Column(Integer, primary_key=True, index=True)

    # Ownership
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    owner = relationship("User", backref="runners")

    # Identity and configuration
    name = Column(String, nullable=False)  # User-editable, unique per owner
    availability_policy = Column(String, nullable=False, default="always_on")  # always_on|on_demand|ephemeral
    labels = Column(MutableDict.as_mutable(JSON), nullable=True)  # e.g. {"role": "laptop", "env": "prod"}
    capabilities = Column(
        MutableList.as_mutable(JSON), nullable=False, default=lambda: ["exec.readonly"]
    )  # e.g. ["exec.readonly"], ["exec.full", "docker"]

    # Connection state
    status = Column(String, nullable=False, default="offline")  # online|offline|revoked
    last_seen_at = Column(DateTime, nullable=True)

    # Authentication
    auth_secret_hash = Column(String, nullable=False)  # SHA256 hash of runner secret

    # Metadata from runner (hostname, os, arch, version, docker_available, etc.)
    runner_metadata = Column(MutableDict.as_mutable(JSON), nullable=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    jobs = relationship("RunnerJob", back_populates="runner", cascade="all, delete-orphan")


class RunnerEnrollToken(Base):
    """One-time enrollment token for registering a new runner.

    Tokens are created by the API and consumed during runner registration.
    They expire after a short TTL (e.g. 10 minutes) for security.
    """

    __tablename__ = "runner_enroll_tokens"

    id = Column(Integer, primary_key=True, index=True)

    # Ownership
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    owner = relationship("User", backref="runner_enroll_tokens")

    # Token data
    token_hash = Column(String, nullable=False, unique=True, index=True)  # SHA256 hash
    expires_at = Column(DateTime, nullable=False)
    used_at = Column(DateTime, nullable=True)  # Set when token is consumed

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class RunnerJob(Base):
    """Execution job for a runner.

    Represents a single command execution request sent to a runner.
    Includes audit trail and output truncation for safety.
    """

    __tablename__ = "runner_jobs"

    id = Column(String, primary_key=True)  # UUID as string

    # Ownership and correlation
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    owner = relationship("User", backref="runner_jobs")

    correlation_id = Column(String, nullable=True, index=True)
    run_id = Column(String, nullable=True)  # Link to run context

    # Runner assignment
    runner_id = Column(Integer, ForeignKey("runners.id", ondelete="CASCADE"), nullable=False, index=True)
    runner = relationship("Runner", back_populates="jobs")

    # Job specification
    command = Column(Text, nullable=False)
    timeout_secs = Column(Integer, nullable=False)

    # Execution state
    status = Column(String, nullable=False, default="queued")  # queued|running|success|failed|timeout|canceled
    exit_code = Column(Integer, nullable=True)

    # Timing
    started_at = Column(DateTime, nullable=True)
    finished_at = Column(DateTime, nullable=True)

    # Output (truncated/capped for safety)
    stdout_trunc = Column(Text, nullable=True)
    stderr_trunc = Column(Text, nullable=True)

    # Error handling
    error = Column(Text, nullable=True)

    # Future: file upload support
    artifacts = Column(MutableDict.as_mutable(JSON), nullable=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)


class RunnerHealthIncident(Base):
    """Durable runner health incident for deduped alerts and wakeups."""

    __tablename__ = "runner_health_incidents"
    __table_args__ = (
        Index("ix_runner_health_incidents_runner_status", "runner_id", "status"),
        Index("ix_runner_health_incidents_owner_status", "owner_id", "status"),
        Index("ix_runner_health_incidents_opened", "opened_at"),
    )

    id = Column(Integer, primary_key=True, index=True)

    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    owner = relationship("User", backref=backref("runner_health_incidents", cascade="all, delete-orphan"))

    runner_id = Column(Integer, ForeignKey("runners.id", ondelete="CASCADE"), nullable=False, index=True)
    runner = relationship("Runner", backref=backref("health_incidents", cascade="all, delete-orphan"))

    incident_type = Column(String, nullable=False, default="offline")
    status = Column(String, nullable=False, default="open")  # open|resolved
    reason_code = Column(String, nullable=False)
    summary = Column(Text, nullable=True)
    context = Column(MutableDict.as_mutable(JSON), nullable=True)

    opened_at = Column(DateTime, server_default=func.now(), nullable=False)
    last_observed_at = Column(DateTime, server_default=func.now(), nullable=False)
    resolved_at = Column(DateTime, nullable=True)

    alert_sent_at = Column(DateTime, nullable=True)
    alert_channel = Column(String, nullable=True)
    alert_count = Column(Integer, nullable=False, default=0)

    wakeup_sent_at = Column(DateTime, nullable=True)
    wakeup_count = Column(Integer, nullable=False, default=0)


# ---------------------------------------------------------------------------
# Knowledge Base – Sources and Documents (Phase 0)
# ---------------------------------------------------------------------------


class KnowledgeSource(Base):
    """User-owned knowledge source (URL, git repo, upload, etc.).

    Each source syncs on a schedule and produces searchable documents.
    Phase 0 only supports 'url' type.
    """

    __tablename__ = "knowledge_sources"

    id = Column(Integer, primary_key=True, index=True)

    # Ownership - every source belongs to one user
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    owner = relationship("User", backref="knowledge_sources")

    # Source type: "url" (Phase 0), "git_repo", "upload", "manual_note" (Phase 1+)
    source_type = Column(String(50), nullable=False)

    # User-friendly label
    name = Column(String(255), nullable=False)

    # Type-specific configuration (e.g., {"url": "...", "auth_header": "..."})
    config = Column(MutableDict.as_mutable(JSON), nullable=False)

    # Optional cron expression for automatic sync (e.g., "0 * * * *" for hourly)
    sync_schedule = Column(String(100), nullable=True)

    # Sync state
    last_synced_at = Column(DateTime, nullable=True)
    sync_status = Column(String(50), default="pending", nullable=False)  # pending, success, failed
    sync_error = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    documents = relationship("KnowledgeDocument", back_populates="source", cascade="all, delete-orphan")


class KnowledgeDocument(Base):
    """A single document fetched from a knowledge source.

    Stores normalized text content for searching.
    """

    __tablename__ = "knowledge_documents"
    __table_args__ = (
        # Ensure one document per (source, path) combination
        UniqueConstraint("source_id", "path", name="uq_source_path"),
    )

    id = Column(Integer, primary_key=True, index=True)

    # Foreign key to source (CASCADE delete when source is removed)
    source_id = Column(Integer, ForeignKey("knowledge_sources.id", ondelete="CASCADE"), nullable=False, index=True)

    # Denormalized owner_id for efficient querying
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Original path/URL
    path = Column(String(1024), nullable=False)

    # Extracted or inferred title
    title = Column(String(512), nullable=True)

    # Normalized text content (searchable)
    content_text = Column(Text, nullable=False)

    # SHA-256 hash for change detection
    content_hash = Column(String(64), nullable=False)

    # Additional metadata (mime type, size, etc.)
    # Note: Named "doc_metadata" to avoid conflict with SQLAlchemy's reserved "metadata"
    doc_metadata = Column(MutableDict.as_mutable(JSON), nullable=True, default={})

    # When this document was last fetched
    fetched_at = Column(DateTime, nullable=False)

    # Relationships
    source = relationship("KnowledgeSource", back_populates="documents")
    owner = relationship("User", backref="knowledge_documents")


# ---------------------------------------------------------------------------
# User Tasks – agent-created tasks for users
# ---------------------------------------------------------------------------


class UserTask(Base):
    """A task created by an agent for a user.

    Agents can use task management tools to create, update, and track
    tasks for their users. This provides a lightweight task management
    system without external dependencies.
    """

    __tablename__ = "user_tasks"

    id = Column(Integer, primary_key=True, index=True)

    # Foreign key to user (CASCADE delete when user is removed)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Task details
    title = Column(Text, nullable=False)
    notes = Column(Text, nullable=True)

    # Status: pending, done, cancelled
    status = Column(String(20), nullable=False, default="pending")

    # Optional due date
    due_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    user = relationship("User", backref="user_tasks")


# ---------------------------------------------------------------------------
# User Skills – DB-backed SKILL.md content per user
# ---------------------------------------------------------------------------


class UserSkill(Base):
    """User-managed skill stored in the database.

    Content is the full SKILL.md text (YAML frontmatter + markdown body).
    Name is stored separately for indexing and uniqueness per user.
    """

    __tablename__ = "user_skills"

    id = Column(Integer, primary_key=True, index=True)

    # Ownership
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Skill identity (unique per user)
    name = Column(String(128), nullable=False)

    # Canonical SKILL.md content
    content = Column(Text, nullable=False)

    # Soft toggle for eligibility/visibility
    is_active = Column(Boolean, default=True, nullable=False)

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relationships
    owner = relationship("User", backref="user_skills")

    __table_args__ = (
        UniqueConstraint("owner_id", "name", name="uq_user_skills_owner_name"),
        Index("ix_user_skills_owner_name", "owner_id", "name"),
    )


# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Memory Files – Virtual filesystem for long-term agent memory
# ---------------------------------------------------------------------------


class MemoryFile(Base):
    """Durable memory file backed by the Runtime Host database.

    Acts as a virtual filesystem entry (path + content) scoped per user.
    """

    __tablename__ = "memory_files"

    id = Column(Integer, primary_key=True, index=True)

    # Ownership
    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)

    # Virtual filesystem path (unique per owner)
    path = Column(String(512), nullable=False)

    # Optional metadata
    title = Column(String(255), nullable=True)
    content = Column(Text, nullable=False)
    tags = Column(MutableList.as_mutable(JSON), nullable=True, default=lambda: [])
    file_metadata = Column(MutableDict.as_mutable(JSON), nullable=True, default=lambda: {})

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)
    last_accessed_at = Column(DateTime, nullable=True)

    # Relationships
    owner = relationship("User", backref="memory_files")

    __table_args__ = (
        UniqueConstraint("owner_id", "path", name="uq_memory_owner_path"),
        Index("ix_memory_owner_path", "owner_id", "path"),
    )


class MemoryEmbedding(Base):
    """Embeddings for MemoryFile content (stored separately for modularity)."""

    __tablename__ = "memory_embeddings"

    id = Column(Integer, primary_key=True, index=True)

    owner_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    memory_file_id = Column(Integer, ForeignKey("memory_files.id", ondelete="CASCADE"), nullable=False, index=True)

    model = Column(String(128), nullable=False)
    embedding = Column(LargeBinary, nullable=False)

    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    owner = relationship("User", backref="memory_embeddings")
    memory_file = relationship("MemoryFile", backref=backref("embeddings", passive_deletes=True))

    __table_args__ = (UniqueConstraint("owner_id", "memory_file_id", "model", name="uq_memory_embedding"),)


# ---------------------------------------------------------------------------
# Rate Limiting – Atomic daily counters for external action tools
# ---------------------------------------------------------------------------


class UserDailyEmailCounter(Base):
    """Atomic daily email counter for rate limiting.

    Uses SELECT FOR UPDATE to prevent race conditions in concurrent sends.
    Count is incremented BEFORE sending to reserve slots atomically.
    """

    __tablename__ = "user_daily_email_counter"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    date = Column(Date, nullable=False)  # UTC date
    count = Column(Integer, nullable=False, server_default="0")

    # Relationships
    user = relationship("User", backref="daily_email_counters")

    __table_args__ = (
        # One counter per user per date
        UniqueConstraint("user_id", "date", name="uq_email_counter_user_date"),
    )


class UserDailySmsCounter(Base):
    """Atomic daily SMS counter for rate limiting.

    Uses SELECT FOR UPDATE to prevent race conditions in concurrent sends.
    Count is incremented BEFORE sending to reserve slots atomically.
    """

    __tablename__ = "user_daily_sms_counter"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    date = Column(Date, nullable=False)  # UTC date
    count = Column(Integer, nullable=False, server_default="0")

    # Relationships
    user = relationship("User", backref="daily_sms_counters")

    __table_args__ = (
        # One counter per user per date
        UniqueConstraint("user_id", "date", name="uq_sms_counter_user_date"),
    )


# ---------------------------------------------------------------------------
# Audit Logging – Track external actions for debugging/compliance
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Email Secrets – Encrypted SES credentials for instance email
# ---------------------------------------------------------------------------


class EmailSecret(Base):
    """Encrypted email config secret (SES creds + sender/recipient).

    One row per (owner, key) for the well-known email keys defined in
    ``zerg.shared.email`` (AWS_SES_ACCESS_KEY_ID, FROM_EMAIL, etc.).
    Resolution order: DB first, env var fallback (self-hosted compatibility).
    """

    __tablename__ = "email_secrets"
    __table_args__ = (UniqueConstraint("owner_id", "key", name="uix_email_secret_owner_key"),)

    id = Column(Integer, primary_key=True, index=True)

    owner_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    key = Column(String(255), nullable=False)  # e.g. "AWS_SES_ACCESS_KEY_ID"
    encrypted_value = Column(Text, nullable=False)  # Fernet AES-GCM
    description = Column(String(500), nullable=True)  # Optional hint for UI

    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    owner = relationship("User", backref="email_secrets")


class EmailSendLog(Base):
    """Audit log for sent emails.

    Records each email send for debugging and compliance purposes.
    Not used for rate limiting (counters handle that).
    """

    __tablename__ = "email_send_log"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    to_email = Column(String(255), nullable=False)
    sent_at = Column(DateTime, server_default=func.now(), nullable=False)

    # Relationships
    user = relationship("User", backref="email_send_logs")

    __table_args__ = (
        # Index for querying user's sent emails by time
        Index("ix_email_send_log_user_sent", "user_id", "sent_at"),
    )


# ---------------------------------------------------------------------------
# Scenario Seeding – Track seeded scenarios for idempotency
# ---------------------------------------------------------------------------


class SeedRegistry(Base):
    """Registry of seeded scenarios for deterministic, idempotent seeding.

    Tracks which scenarios have been seeded to prevent duplicates.
    Uses deterministic UUIDs (uuid5) for all seeded entities.
    """

    __tablename__ = "seed_registry"

    id = Column(Integer, primary_key=True, index=True)

    # Seed key: unique identifier for this seeded entity
    # Format: "{scenario_name}:{entity_type}:{entity_ref}"
    # Example: "swarm-mvp:thread:thread-1"
    seed_key = Column(String(255), nullable=False)

    # Target: where this was seeded (db path or identifier)
    # Examples: "dev", "test", "demo_db", "/path/to/db.sqlite"
    target = Column(String(255), nullable=False)

    # Namespace: category of seeding operation
    # Examples: "demo", "test", "marketing"
    namespace = Column(String(50), nullable=False, server_default="test")

    # Entity details
    entity_type = Column(String(50), nullable=False)  # thread, run, message, event, etc.
    entity_id = Column(String(255), nullable=True)  # The actual ID of the created entity

    # Timestamps
    created_at = Column(DateTime, server_default=func.now(), nullable=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), nullable=False)

    __table_args__ = (
        # Ensure each seed_key is unique per target
        UniqueConstraint("seed_key", "target", name="uq_seed_registry_key_target"),
        Index("ix_seed_registry_namespace", "namespace"),
        Index("ix_seed_registry_target", "target"),
    )
