#!/usr/bin/env python3
"""Generate Python tool contract enums from schemas/tools.yml."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPO_ROOT / "schemas" / "tools.yml"
OUTPUT_PATH = REPO_ROOT / "server" / "zerg" / "tools" / "generated" / "tool_definitions.py"


def _enum_member(value: str) -> str:
    member = re.sub(r"[^0-9A-Za-z]+", "_", value).strip("_").upper()
    if not member:
        raise ValueError(f"Cannot generate enum member for empty value: {value!r}")
    if member[0].isdigit():
        member = f"_{member}"
    return member


def _schema(data: dict[str, Any], name: str) -> dict[str, Any]:
    return data["components"]["schemas"][name]


def main() -> int:
    data = yaml.safe_load(SCHEMA_PATH.read_text()) or {}
    tool_names = list(_schema(data, "ToolName")["enum"])
    server_names = list(_schema(data, "ServerName")["enum"])
    mappings = dict(_schema(data, "ToolRegistry")["properties"]["tool_mappings"]["properties"])

    missing = [name for name in tool_names if name not in mappings]
    if missing:
        raise ValueError(f"ToolRegistry.tool_mappings is missing tool(s): {', '.join(missing)}")

    unknown_servers = sorted({entry["const"] for entry in mappings.values()} - set(server_names))
    if unknown_servers:
        raise ValueError(f"ToolRegistry.tool_mappings references unknown server(s): {', '.join(unknown_servers)}")

    lines: list[str] = [
        "# Generated by scripts/generate_tool_types.py - DO NOT EDIT MANUALLY",
        "",
        "from enum import Enum",
        "from typing import Dict",
        "from typing import Optional",
        "",
        "",
        "class ToolName(str, Enum):",
        '    """Built-in tool names available in the registry."""',
        "",
    ]
    for tool_name in tool_names:
        lines.append(f'    {_enum_member(tool_name)} = "{tool_name}"')

    lines.extend(
        [
            "",
            "",
            "class ServerName(str, Enum):",
            '    """Server/module names for tools."""',
            "",
        ]
    )
    for server_name in server_names:
        lines.append(f'    {_enum_member(server_name)} = "{server_name}"')

    lines.extend(
        [
            "",
            "",
            "# Tool to server mapping for validation",
            "TOOL_SERVER_MAPPING: Dict[ToolName, ServerName] = {",
        ]
    )
    for tool_name in tool_names:
        server_name = mappings[tool_name]["const"]
        lines.append(f"    ToolName.{_enum_member(tool_name)}: ServerName.{_enum_member(server_name)},")

    lines.extend(
        [
            "}",
            "",
            "",
            "class ToolValidator:",
            '    """Validate tool names and server mappings."""',
            "",
            "    @staticmethod",
            "    def is_valid_tool(name: str) -> bool:",
            "        try:",
            "            ToolName(name)",
            "            return True",
            "        except ValueError:",
            "            return False",
            "",
            "    @staticmethod",
            "    def get_server_for_tool(name: str) -> Optional[str]:",
            "        try:",
            "            tool_enum = ToolName(name)",
            "        except ValueError:",
            "            return None",
            "        return TOOL_SERVER_MAPPING[tool_enum].value",
            "",
            "    @staticmethod",
            "    def validate_tool_server_mapping(tool_name: str, server_name: str) -> bool:",
            "        expected = ToolValidator.get_server_for_tool(tool_name)",
            "        return expected == server_name",
            "",
        ]
    )

    OUTPUT_PATH.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
