openapi: 3.0.3

info:
  title: Longhouse API
  version: 1.0.0
  description: |
    Complete REST API schema for Longhouse.
    Single source of truth for all HTTP endpoints.

servers:
  - url: http://localhost:8001
    description: Development server

# ==============================================================================
# SHARED SCHEMAS - These should match your database models exactly
# ==============================================================================

components:
  schemas:
    # -------------------------------------------------------------------------
    # Core Domain Models (these are your actual data structures)
    # -------------------------------------------------------------------------

    Fiche:
      type: object
      required: [id, name, system_instructions, task_instructions, model]
      properties:
        id:
          type: integer
          minimum: 1
        name:
          type: string
          minLength: 1
        system_instructions:
          type: string
        task_instructions:
          type: string
        model:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Thread:
      type: object
      required: [id, title, fiche_id]
      properties:
        id:
          type: integer
          minimum: 1
        title:
          type: string
          minLength: 1
        fiche_id:
          type: integer
          minimum: 1
        created_at:
          type: string
          format: date-time

    Message:
      type: object
      required: [id, role, content]
      properties:
        id:
          type: integer
          minimum: 1
        role:
          type: string
          enum: [user, assistant, system, tool]
        content:
          type: string
        metadata:
          type: object
          additionalProperties: true
        created_at:
          type: string
          format: date-time

    # -------------------------------------------------------------------------
    # Request/Response Wrappers
    # -------------------------------------------------------------------------

    CreateFicheRequest:
      type: object
      required: [system_instructions, task_instructions, model]
      properties:
        system_instructions:
          type: string
          minLength: 1
        task_instructions:
          type: string
        model:
          type: string

    ErrorResponse:
      type: object
      required: [error, message]
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true

# ==============================================================================
# API ENDPOINTS - Cover ALL your REST endpoints
# ==============================================================================

paths:
  # -------------------------------------------------------------------------
  # Fiche Operations
  # -------------------------------------------------------------------------

  /api/fiches:
    get:
      summary: List fiches
      parameters:
        - name: scope
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of fiches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fiche'

    post:
      summary: Create fiche
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFicheRequest'
      responses:
        '201':
          description: Fiche created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fiche'

  /api/fiches/{fiche_id}:
    parameters:
      - name: fiche_id
        in: path
        required: true
        schema:
          type: integer
          minimum: 1

    get:
      summary: Get fiche by ID
      responses:
        '200':
          description: Fiche details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fiche'

    put:
      summary: Update fiche
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFicheRequest'
      responses:
        '200':
          description: Fiche updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fiche'

    delete:
      summary: Delete fiche
      responses:
        '204':
          description: Fiche deleted

  # -------------------------------------------------------------------------
  # Thread Operations
  # -------------------------------------------------------------------------

  /api/threads:
    get:
      summary: List threads
      parameters:
        - name: fiche_id
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: List of threads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Thread'

  /api/threads/{thread_id}/messages:
    parameters:
      - name: thread_id
        in: path
        required: true
        schema:
          type: integer
          minimum: 1

    get:
      summary: Get thread messages
      responses:
        '200':
          description: Thread messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'

    post:
      summary: Create thread message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [content]
              properties:
                content:
                  type: string
                  minLength: 1
      responses:
        '201':
          description: Message created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
