"""add_llm_audit_log

Revision ID: 7799c1632888
Revises: 12e00ff4d7fa
Create Date: 2026-01-13 15:34:11.351682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7799c1632888'
down_revision: Union[str, Sequence[str], None] = '12e00ff4d7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=True),
    sa.Column('response_tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['agent_threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_audit_log_run_id'), 'llm_audit_log', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_audit_log_worker_id'), 'llm_audit_log', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_audit_log_worker_id'), table_name='llm_audit_log')
    op.drop_index(op.f('ix_llm_audit_log_run_id'), table_name='llm_audit_log')
    op.drop_table('llm_audit_log')
    # ### end Alembic commands ###
