# Product Demo Scenario
# Hook → Wow → Explain → CTA structure (~45s total)
#
# Usage:
#   1. Generate audio first:  make video-audio
#   2. Record video:          make video-record
#   3. Process/combine:       make video-process

name: product-demo
description: Product demo — hook, chat wow moment, explain with automation, canvas, CTA

voiceover:
  voice: "nova"  # Options: alloy, ash, ballad, coral, echo, fable, nova, onyx, sage, shimmer, verse
  model: "gpt-4o-mini-tts"  # Latest model (March 2025+)

# Golden conversation data for replay mode
# These get inserted as real ThreadMessage rows when replay mode is active
golden_conversations:
  morning-briefing:
    user_message: "Good morning! Give me a quick briefing on my day."
    messages:
      - role: assistant
        content: "Good morning! Let me pull together your briefing..."
        delay_ms: 400
      - role: tool_use
        name: spawn_worker
        input:
          worker_name: "daily-briefing"
          task: "Gather calendar events, weather, and priority tasks"
        delay_ms: 200
    worker_result:
      delay_ms: 2500
      worker_name: "daily-briefing"
      status: "complete"
      result: |
        Calendar: Team standup at 10am, Design review at 2pm
        Weather: 68°F, partly cloudy
        Tasks: 3 high priority items due today
    final_message:
      role: assistant
      content: |
        Here's your morning briefing:

        **Schedule**
        - 10:00 AM — Team standup
        - 2:00 PM — Design review

        **Weather**
        68°F and partly cloudy — perfect day!

        **Priority Tasks**
        You have 3 high-priority items due today. Would you like me to show them?
      delay_ms: 600

  automate-reports:
    user_message: "Can you set up an automation to send me weekly reports every Monday?"
    messages:
      - role: assistant
        content: "I'll create a workflow to automate your weekly reports..."
        delay_ms: 500
      - role: tool_use
        name: spawn_worker
        input:
          worker_name: "workflow-builder"
          task: "Create weekly report automation with Monday schedule"
        delay_ms: 200
    worker_result:
      delay_ms: 3000
      worker_name: "workflow-builder"
      status: "complete"
      result: |
        Created workflow: "Weekly Report Automation"
        Trigger: Every Monday at 9:00 AM
        Actions: Gather metrics → Generate report → Send email
    final_message:
      role: assistant
      content: |
        Done! I've created your **Weekly Report Automation** workflow.

        **Schedule:** Every Monday at 9:00 AM
        **Actions:**
        1. Gather your weekly metrics
        2. Generate a formatted report
        3. Send it to your email

        You can view and customize this workflow in the Canvas. Want me to take you there?
      delay_ms: 500

# Scene definitions with steps
scenes:
  # Scene 1: Hook (~4s) — Bold claim, brand title card
  - id: hook
    voiceover: |
      What if your AI assistant actually assisted?
    steps:
      - action: navigate
        url: /title-card.html?h=What+if+your+AI+assistant+<span+class="accent">actually+assisted</span>%3F&s=&style=brand
        wait_for: '[data-ready="true"]'
      - action: pause
        duration_ms: 500
      - action: pause_for_audio

  # Scene 2: Chat Wow (~8s) — Jump into chat, fast typing, show response streaming
  - id: chat-wow
    voiceover: |
      One question. Calendar, weather, tasks. Handled.
    golden_conversation: morning-briefing
    steps:
      - action: navigate
        url: /chat?thread=briefing&marketing=true&replay=product-demo&effects=off&clock=frozen
        wait_for: '[data-testid="chat-input"]'
      - action: pause
        duration_ms: 300
      - action: type
        selector: '[data-testid="chat-input"]'
        text: "Good morning! Give me a quick briefing on my day."
        delay_ms: 35
      - action: pause
        duration_ms: 200
      - action: click
        selector: '[data-testid="send-message-btn"]'
      - action: pause
        duration_ms: 2500
      - action: wait
        selector: '.message-group:last-child .message.assistant'
        timeout_ms: 15000
      - action: pause_for_audio

  # Scene 3: Chat Explain (~12s) — Slow down, explain the product, show automation
  - id: chat-explain
    voiceover: |
      Longhouse is your AI automation platform.
      Ask anything in plain English.
      It coordinates agents, tools, and workflows.
      No menus. No config files. Just results.
    golden_conversation: automate-reports
    steps:
      - action: navigate
        url: /chat?thread=automation&marketing=true&replay=product-demo&effects=off&clock=frozen
        wait_for: '[data-testid="chat-input"]'
      - action: pause
        duration_ms: 500
      - action: type
        selector: '[data-testid="chat-input"]'
        text: "Can you set up an automation to send me weekly reports every Monday?"
        delay_ms: 30
      - action: pause
        duration_ms: 300
      - action: click
        selector: '[data-testid="send-message-btn"]'
      - action: pause
        duration_ms: 3500
      - action: wait
        selector: '.message-group:last-child .message.assistant'
        timeout_ms: 15000
      - action: pause_for_audio

  # Scene 4: Dashboard (~10s) — Show agents and automations at a glance
  - id: dashboard-view
    voiceover: |
      Your dashboard shows every agent, every automation, at a glance.
      Status, history, performance — one view.
    steps:
      - action: navigate
        url: /dashboard?marketing=true&replay=product-demo&effects=off&clock=frozen
        wait_for: '[data-ready="true"]'
      - action: pause
        duration_ms: 2000
      - action: pause_for_audio
      - action: pause
        duration_ms: 2000

  # Scene 5: CTA (~6s) — Self-hosted pitch, brand title card
  - id: cta
    voiceover: |
      Self-hosted. Your data, your agents, your rules.
      Get started at longhouse dot ai.
    steps:
      - action: navigate
        url: /title-card.html?h=Your+data.+Your+agents.+<span+class="accent">Your+rules.</span>&s=Self-hosted+AI+automation.+Get+started+free.&style=brand
        wait_for: '[data-ready="true"]'
      - action: pause
        duration_ms: 500
      - action: pause_for_audio
      - action: pause
        duration_ms: 2000
