//! Managed-identity vocabulary, generated from the provider schema.
//!
//! @generated by scripts/generate/managed_identity_contract_rs.py -- DO NOT EDIT.
//! Source: schemas/managed_providers.yml
//! Regenerate with `make generate-managed-identity`.

#![allow(dead_code)]

/// A provider Longhouse can launch. One variant per `launch_local` row in
/// the schema, so a provider added there cannot be silently missing from a
/// match arm.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ManagedProvider {
    /// `antigravity`
    Antigravity,
    /// `claude`
    Claude,
    /// `codex`
    Codex,
    /// `cursor`
    Cursor,
    /// `opencode`
    Opencode,
    /// `pi`
    Pi,
}

impl ManagedProvider {
    /// The wire name. This is the value of `LONGHOUSE_MANAGED_PROVIDER`.
    pub const fn as_str(self) -> &'static str {
        match self {
            ManagedProvider::Antigravity => "antigravity",
            ManagedProvider::Claude => "claude",
            ManagedProvider::Codex => "codex",
            ManagedProvider::Cursor => "cursor",
            ManagedProvider::Opencode => "opencode",
            ManagedProvider::Pi => "pi",
        }
    }
}

/// Every launchable provider, in schema order.
pub const ALL_MANAGED_PROVIDERS: &[ManagedProvider] = &[
    ManagedProvider::Antigravity,
    ManagedProvider::Claude,
    ManagedProvider::Codex,
    ManagedProvider::Cursor,
    ManagedProvider::Opencode,
    ManagedProvider::Pi,
];

/// Keys the overlay always sets on a managed provider process.
pub const REQUIRED_IDENTITY_KEYS: &[&str] = &[
    "LONGHOUSE_MANAGED_SESSION_ID",
    "LONGHOUSE_MANAGED_PROVIDER",
];

/// Keys a provider process never inherits. The overlay scrubs all of them;
/// a launcher then sets back only the ones it owns.
pub const NEVER_INHERITED_KEYS: &[&str] = &[
    "LONGHOUSE_SESSION_ID",
    "LONGHOUSE_MANAGED_SESSION_ID",
    "LONGHOUSE_MANAGED_PROVIDER",
    "LONGHOUSE_RUN_ID",
    "LONGHOUSE_CHANNEL_SESSION_ID",
    "LONGHOUSE_CHANNEL_CWD",
    "LONGHOUSE_PROVIDER_SESSION_ID",
    "LONGHOUSE_COORDINATION_TOKEN",
    "LONGHOUSE_HOOK_URL",
    "LONGHOUSE_HOOK_TOKEN",
    "LONGHOUSE_PERMISSION_HOOK_ENABLED",
    "LONGHOUSE_LAUNCH_ACTOR",
    "LONGHOUSE_LAUNCH_SURFACE",
    "LONGHOUSE_CURSOR_LAUNCH_ID",
    "LONGHOUSE_CURSOR_REGISTRATION_READY",
    "LONGHOUSE_CURSOR_PRINT_MODE",
    "LONGHOUSE_ANTIGRAVITY_STATE_DIR",
    "LONGHOUSE_ANTIGRAVITY_INBOX_DIR",
];
