//! Wire-phase vocabulary, generated from the managed phase contract.
//!
//! @generated by scripts/generate/managed_phase_contract_rs.py -- DO NOT EDIT.
//! Source: server/zerg/config/managed_phase_contract.json
//! Regenerate with `make generate-phase-contract`.

#![allow(dead_code)]

/// `thinking` -- attention: working (wire).
pub const PHASE_THINKING: &str = "thinking";
/// `running` -- attention: working (wire).
pub const PHASE_RUNNING: &str = "running";
/// `blocked` -- attention: blocked (wire).
pub const PHASE_BLOCKED: &str = "blocked";
/// `needs_user` -- attention: idle (wire).
pub const PHASE_NEEDS_USER: &str = "needs_user";
/// `stalled` -- attention: blocked (wire).
pub const PHASE_STALLED: &str = "stalled";
/// `idle` -- attention: idle (wire).
pub const PHASE_IDLE: &str = "idle";
/// `finished` -- attention: idle (local health only).
pub const PHASE_FINISHED: &str = "finished";

/// Phases an adapter may put on the wire. Ingest rejects anything else.
pub const WIRE_PHASES: &[&str] = &[
    PHASE_THINKING,
    PHASE_RUNNING,
    PHASE_BLOCKED,
    PHASE_NEEDS_USER,
    PHASE_STALLED,
    PHASE_IDLE,
];

/// Phases that never cross the wire; they exist only in local health.
pub const LOCAL_HEALTH_ONLY_PHASES: &[&str] = &[PHASE_FINISHED];

/// Is this a phase an adapter is allowed to ship?
pub fn is_wire_phase(value: &str) -> bool {
    WIRE_PHASES.contains(&value)
}
