from datetime import datetime
from enum import Enum
from typing import Any
from typing import Dict
from typing import List
from typing import Optional

from pydantic import AliasChoices

# ---------------------------------------------------------------------------
# New *Run History* schemas
# ---------------------------------------------------------------------------
from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field

from zerg.models.enums import RunStatus
from zerg.models.enums import RunTrigger
from zerg.utils.time import UTCBaseModel


# Automation schemas
class AutomationStatus(str, Enum):
    IDLE = "idle"
    RUNNING = "running"
    ERROR = "error"
    PROCESSING = "processing"


class AutomationBase(BaseModel):
    name: str
    system_instructions: str
    task_instructions: str
    model: str
    schedule: Optional[str] = None
    config: Optional[Dict[str, Any]] = None
    last_error: Optional[str] = None
    allowed_tools: Optional[List[str]] = None


class AutomationCreate(BaseModel):
    """Schema for automation creation. Name is auto-generated by backend."""

    # name field omitted - backend auto-generates "New Automation"
    system_instructions: str
    task_instructions: str
    model: str
    schedule: Optional[str] = None
    config: Optional[Dict[str, Any]] = None
    allowed_tools: Optional[List[str]] = None


class AutomationUpdate(BaseModel):
    name: Optional[str] = None
    system_instructions: Optional[str] = None
    task_instructions: Optional[str] = None
    model: Optional[str] = None
    status: Optional[AutomationStatus] = None
    schedule: Optional[str] = None
    config: Optional[Dict[str, Any]] = None
    last_error: Optional[str] = None
    allowed_tools: Optional[List[str]] = None


# ---------------------------------------------------------------------------
# Pydantic 2.x quirk: on some Python versions ForwardRef resolution fails when
# schema is imported *before* all referenced types are defined.  Calling
# `.model_rebuild()` ensures the internal TypeAdapter tree is fully resolved.
# This is a no-op if everything is already valid.
for _m in [AutomationCreate]:
    try:
        _m.model_rebuild()
    except Exception:  # pragma: no cover – defensive only
        pass


class AutomationMessage(UTCBaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    role: str
    content: str
    timestamp: datetime


# ------------------------------------------------------------
# Authentication schemas (Stage 1)
# ------------------------------------------------------------


class UserOut(UTCBaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    email: str
    is_active: bool
    created_at: datetime
    display_name: Optional[str] = None
    avatar_url: Optional[str] = None
    prefs: Optional[Dict[str, Any]] = None
    last_login: Optional[datetime] = None
    role: str = "USER"


# User profile update schema (partial)
class UserUpdate(BaseModel):
    display_name: Optional[str] = None
    avatar_url: Optional[str] = None
    prefs: Optional[Dict[str, Any]] = None


class TokenOut(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int  # seconds until expiry


# Thread Message schemas
class ThreadMessageBase(BaseModel):
    role: str
    content: str
    tool_calls: Optional[List[Dict[str, Any]]] = None
    tool_call_id: Optional[str] = None
    name: Optional[str] = None
    message_metadata: Optional[Dict[str, Any]] = None


class ThreadMessageCreate(ThreadMessageBase):
    sent_at: Optional[datetime] = None  # Client can provide send timestamp; server validates ±5min, or uses server time


class ThreadMessageResponse(UTCBaseModel, ThreadMessageBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    thread_id: int
    sent_at: datetime  # When message was sent (UTC, timezone-aware)
    processed: bool = False
    parent_id: Optional[int] = None
    # Fields for message type and tool display
    message_type: Optional[str] = None
    tool_name: Optional[str] = None


# Thread schemas
class ThreadBase(BaseModel):
    title: str
    automation_state: Optional[Dict[str, Any]] = Field(
        default=None,
        validation_alias=AliasChoices("automation_state", "fiche_state"),
    )
    active: Optional[bool] = True
    thread_type: Optional[str] = "chat"  # Types: chat, scheduled, manual


class ThreadCreate(ThreadBase):
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))


class ThreadUpdate(BaseModel):
    title: Optional[str] = None
    automation_state: Optional[Dict[str, Any]] = Field(
        default=None,
        validation_alias=AliasChoices("automation_state", "fiche_state"),
    )
    active: Optional[bool] = None
    thread_type: Optional[str] = None


class Thread(UTCBaseModel, ThreadBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    created_at: datetime
    updated_at: datetime
    messages: List[ThreadMessageResponse] = []


class ThreadSummary(UTCBaseModel, ThreadBase):
    """Thread summary for list endpoints (no messages payload)."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    created_at: datetime
    updated_at: datetime


class Automation(UTCBaseModel, AutomationBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    owner_id: int
    owner: Optional[UserOut] = None
    status: AutomationStatus
    created_at: datetime
    updated_at: datetime
    messages: List[AutomationMessage] = []
    # Deprecated field removed – scheduling is implied by `schedule`.
    next_run_at: Optional[datetime] = None
    last_run_at: Optional[datetime] = None
    last_error: Optional[str] = None
    # Display type for UI (Phase 2 terminology rebrand)
    display_type: str = "automation"


# ---------------------------------------------------------------------------
# Automation Details schema (wrapper used by /automations/{id}/details endpoint)
# ---------------------------------------------------------------------------


class AutomationDetails(BaseModel):
    """Envelope object returned by the automation *details* REST endpoint.

    In Phase 1 we only populate the mandatory ``automation`` field.  The optional
    ``threads``, ``runs`` and ``stats`` keys are included so that the response
    shape is forwards-compatible with the richer payloads planned for future
    phases (see *fiche_debug_modal_design.md*).
    """

    automation: Automation = Field(validation_alias=AliasChoices("automation", "fiche"))
    # The following fields will be filled in future phases when the client
    # requests additional includes via the `include` query param.
    threads: Optional[List[Thread]] = None  # noqa: F821 – Thread is declared later in this file
    runs: Optional[List[Any]] = None  # Placeholder for run log entries
    stats: Optional[Dict[str, Any]] = None


# Backwards-compatible aliases for internal imports and untouched compatibility
# surfaces. Public routes should use the Automation* names above.
FicheBase = AutomationBase
FicheCreate = AutomationCreate
FicheUpdate = AutomationUpdate
FicheMessage = AutomationMessage
Fiche = Automation
FicheDetails = AutomationDetails


# Message schemas
class MessageCreate(BaseModel):
    role: str
    content: str


class MessageResponse(UTCBaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    role: str
    content: str
    timestamp: datetime


# ------------------------------------------------------------
# Trigger schemas
# ------------------------------------------------------------


class TriggerBase(BaseModel):
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    type: str = "webhook"
    # Arbitrary configuration for non-webhook triggers (e.g. email server
    # settings).  For webhook triggers this is usually ``null``.
    config: Optional[Dict[str, Any]] = None


class TriggerCreate(TriggerBase):
    # Secret is generated by the server; client cannot supply it.
    pass


class Trigger(UTCBaseModel, TriggerBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    secret: str
    created_at: datetime


# ------------------------------------------------------------
# Run output schema (read-only, hence *Out* suffix)
# ------------------------------------------------------------


# RunStatus moved to models.enums for single source of truth


class RunOut(UTCBaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    thread_id: int
    status: RunStatus
    trigger: RunTrigger
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    duration_ms: Optional[int] = None
    total_tokens: Optional[int] = None
    total_cost_usd: Optional[float] = None
    error: Optional[str] = None
    # Display type for UI (Phase 2 terminology rebrand)
    display_type: str = "run"


# ---------------------------------------------------------------------------
# Dashboard payload schemas
# ---------------------------------------------------------------------------


class RunBundle(BaseModel):
    automation_id: int = Field(validation_alias=AliasChoices("automation_id", "fiche_id"))
    runs: List[RunOut] = []


class DashboardSnapshot(UTCBaseModel):
    scope: str
    fetched_at: datetime
    runs_limit: int
    automations: List[Automation] = Field(validation_alias=AliasChoices("automations", "fiches"))
    runs: List[RunBundle]


# ---------------------------------------------------------------------------
# Knowledge Base schemas (Phase 0)
# ---------------------------------------------------------------------------


class KnowledgeSourceBase(BaseModel):
    name: str
    source_type: str
    config: Dict[str, Any]
    sync_schedule: Optional[str] = None


class KnowledgeSourceCreate(KnowledgeSourceBase):
    pass


class KnowledgeSourceUpdate(BaseModel):
    name: Optional[str] = None
    config: Optional[Dict[str, Any]] = None
    sync_schedule: Optional[str] = None


class KnowledgeSource(UTCBaseModel, KnowledgeSourceBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    owner_id: int
    sync_status: str
    last_synced_at: Optional[datetime] = None
    sync_error: Optional[str] = None
    created_at: datetime
    updated_at: datetime


class KnowledgeDocumentBase(BaseModel):
    path: str
    title: Optional[str] = None
    content_text: str
    content_hash: str
    doc_metadata: Optional[Dict[str, Any]] = None


class KnowledgeDocument(UTCBaseModel, KnowledgeDocumentBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    source_id: int
    owner_id: int
    fetched_at: datetime


class KnowledgeSearchResult(BaseModel):
    """A search result from the knowledge base."""

    source_name: str
    source_id: int
    document_id: int
    path: str
    title: Optional[str] = None
    snippets: List[str]  # Matching text excerpts
    score: float  # Relevance score
    # V1.1: Provenance - immutable permalink to exact version (if available)
    permalink: Optional[str] = None
