#!/bin/sh
# Frontend entrypoint - generates runtime config.js from env vars
#
# For split deploy: Pass API_BASE_URL/WS_BASE_URL (or PUBLIC_API_URL/PUBLIC_WS_URL)
# For monolithic: Don't pass env vars, uses same-origin /api defaults
#
# BACKEND_HOST: Docker hostname for nginx to proxy /api to (default: backend).

CONFIG_FILE="${CONFIG_FILE:-/usr/share/nginx/html/config.js}"
CSP_FILE="${CSP_FILE:-/etc/nginx/csp.conf}"
NGINX_TEMPLATE="${NGINX_TEMPLATE:-/etc/nginx/nginx.conf.template}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/nginx.conf}"

# Set backend host for nginx proxy.
export BACKEND_HOST="${BACKEND_HOST:-backend}"

# Generate nginx.conf from template with envsubst
if [ -f "$NGINX_TEMPLATE" ]; then
  envsubst '${BACKEND_HOST}' < "$NGINX_TEMPLATE" > "$NGINX_CONF"
  echo "Generated nginx.conf with BACKEND_HOST=$BACKEND_HOST"
fi

# Prefer API_BASE_URL / WS_BASE_URL, fall back to PUBLIC_API_URL / PUBLIC_WS_URL
API_ENV="${API_BASE_URL:-${PUBLIC_API_URL:-}}"
WS_ENV="${WS_BASE_URL:-${PUBLIC_WS_URL:-}}"
UMAMI_WEBSITE_ID_VALUE="${UMAMI_WEBSITE_ID:-${VITE_UMAMI_WEBSITE_ID:-}}"
UMAMI_SCRIPT_SRC_VALUE="${UMAMI_SCRIPT_SRC:-${VITE_UMAMI_SCRIPT_SRC:-}}"
UMAMI_DOMAINS_VALUE="${UMAMI_DOMAINS:-${VITE_UMAMI_DOMAINS:-}}"
UMAMI_TAG_VALUE="${UMAMI_TAG:-${VITE_UMAMI_TAG:-prod}}"

# Prefer runtime config for the browser, even in same-origin mode, so
# analytics and split-deploy settings don't require a rebuild.
API="${API_ENV:-}"
WS="${WS_ENV:-}"

# Normalize: strip trailing slashes
API="${API%/}"

# Default WS to API URL with ws(s) protocol + /ws suffix if not set
if [ -n "$API" ] && [ -z "$WS" ]; then
  WS=$(echo "$API" | sed 's|^http|ws|')
  case "$WS" in
    */api) WS="${WS}/ws" ;;
  esac
fi

# Normalize WS: strip trailing slashes
WS="${WS%/}"

# Validate URL format - reject if contains control characters or newlines
# This prevents JS injection via malformed env vars
case "$API" in
  *[[:cntrl:]]*)
    echo "ERROR: API_BASE_URL contains control characters, rejecting"
    API=""
    ;;
esac
case "$WS" in
  *[[:cntrl:]]*)
    echo "ERROR: WS_BASE_URL contains control characters, rejecting"
    WS=""
    ;;
esac
case "$UMAMI_WEBSITE_ID_VALUE" in
  *[[:cntrl:]]*)
    echo "ERROR: UMAMI_WEBSITE_ID contains control characters, rejecting"
    UMAMI_WEBSITE_ID_VALUE=""
    ;;
esac
case "$UMAMI_SCRIPT_SRC_VALUE" in
  *[[:cntrl:]]*)
    echo "ERROR: UMAMI_SCRIPT_SRC contains control characters, rejecting"
    UMAMI_SCRIPT_SRC_VALUE=""
    ;;
esac
case "$UMAMI_DOMAINS_VALUE" in
  *[[:cntrl:]]*)
    echo "ERROR: UMAMI_DOMAINS contains control characters, rejecting"
    UMAMI_DOMAINS_VALUE=""
    ;;
esac
case "$UMAMI_TAG_VALUE" in
  *[[:cntrl:]]*)
    echo "ERROR: UMAMI_TAG contains control characters, rejecting"
    UMAMI_TAG_VALUE=""
    ;;
esac

# Escape special characters for JS string (quotes, backslashes)
# This prevents XSS if env vars contain malicious content
API_ESCAPED=$(printf '%s' "$API" | sed 's/\\/\\\\/g; s/"/\\"/g')
WS_ESCAPED=$(printf '%s' "$WS" | sed 's/\\/\\\\/g; s/"/\\"/g')
UMAMI_WEBSITE_ID_ESCAPED=$(printf '%s' "$UMAMI_WEBSITE_ID_VALUE" | sed 's/\\/\\\\/g; s/"/\\"/g')
UMAMI_SCRIPT_SRC_ESCAPED=$(printf '%s' "$UMAMI_SCRIPT_SRC_VALUE" | sed 's/\\/\\\\/g; s/"/\\"/g')
UMAMI_DOMAINS_ESCAPED=$(printf '%s' "$UMAMI_DOMAINS_VALUE" | sed 's/\\/\\\\/g; s/"/\\"/g')
UMAMI_TAG_ESCAPED=$(printf '%s' "$UMAMI_TAG_VALUE" | sed 's/\\/\\\\/g; s/"/\\"/g')

cat > "$CONFIG_FILE" << EOF
// Runtime configuration - generated by docker-entrypoint.sh
window.API_BASE_URL = "${API_ESCAPED}";
window.WS_BASE_URL = "${WS_ESCAPED}";
window.__UMAMI_WEBSITE_ID__ = "${UMAMI_WEBSITE_ID_ESCAPED}";
window.__UMAMI_SCRIPT_SRC__ = "${UMAMI_SCRIPT_SRC_ESCAPED}";
window.__UMAMI_DOMAINS__ = "${UMAMI_DOMAINS_ESCAPED}";
window.__UMAMI_TAG__ = "${UMAMI_TAG_ESCAPED}";
console.log("Config: API=" + window.API_BASE_URL + " WS=" + window.WS_BASE_URL);
EOF

echo "Generated config.js: API=${API:-same-origin} WS=${WS:-auto} UMAMI=${UMAMI_WEBSITE_ID_VALUE:+on}"

# Generate dynamic CSP based on API_BASE_URL and WS_BASE_URL
# Extract and validate domains (prevent header injection)
API_DOMAIN=""
WS_DOMAIN=""

# Extract API domain
if [ -n "$API" ]; then
  case "$API" in
    http://*|https://*)
      # Extract domain (strip protocol and path)
      API_DOMAIN=$(echo "$API" | sed 's|^https\?://||; s|/.*||')
      # Validate domain contains only allowed characters (alphanumeric, dash, dot, colon for port)
      case "$API_DOMAIN" in
        *[!a-zA-Z0-9.:-]*)
          echo "WARNING: API_BASE_URL contains invalid characters, CSP will use 'self' only"
          API_DOMAIN=""
          ;;
      esac
      ;;
    *)
      echo "WARNING: API_BASE_URL not a valid URL, CSP will use 'self' only"
      ;;
  esac
fi

# Extract WS domain (if different from API)
if [ -n "$WS" ]; then
  case "$WS" in
    ws://*|wss://*)
      WS_DOMAIN=$(echo "$WS" | sed 's|^wss\?://||; s|/.*||')
      # Validate domain
      case "$WS_DOMAIN" in
        *[!a-zA-Z0-9.:-]*)
          echo "WARNING: WS_BASE_URL contains invalid characters"
          WS_DOMAIN=""
          ;;
      esac
      ;;
  esac
fi

# Build connect-src with API and WS domains
CONNECT_SRC="'self' https://accounts.google.com https://analytics.drose.io https://api.openai.com wss://api.openai.com"
SCRIPT_SRC="'self' https://accounts.google.com https://analytics.drose.io https://static.cloudflareinsights.com"
if [ -n "$API_DOMAIN" ]; then
  CONNECT_SRC="$CONNECT_SRC https://$API_DOMAIN wss://$API_DOMAIN"
fi
# Add WS domain if different from API domain
if [ -n "$WS_DOMAIN" ] && [ "$WS_DOMAIN" != "$API_DOMAIN" ]; then
  CONNECT_SRC="$CONNECT_SRC wss://$WS_DOMAIN"
fi

# Allow runtime Umami hosts for both script loading and analytics beacons.
UMAMI_SCRIPT_ORIGIN=""
if [ -n "$UMAMI_SCRIPT_SRC_VALUE" ]; then
  case "$UMAMI_SCRIPT_SRC_VALUE" in
    http://*|https://*)
      UMAMI_SCRIPT_ORIGIN=$(echo "$UMAMI_SCRIPT_SRC_VALUE" | sed -E 's|^(https?://[^/]+)/?.*$|\1|')
      case "$UMAMI_SCRIPT_ORIGIN" in
        *[!a-zA-Z0-9.:/_-]*)
          echo "WARNING: UMAMI_SCRIPT_SRC contains invalid origin characters"
          UMAMI_SCRIPT_ORIGIN=""
          ;;
      esac
      ;;
  esac
fi

if [ -n "$UMAMI_SCRIPT_ORIGIN" ] && [ "$UMAMI_SCRIPT_ORIGIN" != "https://analytics.drose.io" ]; then
  CONNECT_SRC="$CONNECT_SRC $UMAMI_SCRIPT_ORIGIN"
  SCRIPT_SRC="$SCRIPT_SRC $UMAMI_SCRIPT_ORIGIN"
fi

# Always create CSP file (even if empty API) to prevent nginx include failure
cat > "$CSP_FILE" << EOF
add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; frame-ancestors 'self'; object-src 'none'; connect-src $CONNECT_SRC; script-src $SCRIPT_SRC; style-src 'self' 'unsafe-inline' https://accounts.google.com https://fonts.googleapis.com https://api.fontshare.com; font-src 'self' https://fonts.gstatic.com https://cdn.fontshare.com; img-src 'self' data: https: blob:; media-src 'self' blob: data:; frame-src https://accounts.google.com;" always;
EOF

echo "Generated CSP config with connect-src: $CONNECT_SRC"

# Start nginx
exec nginx -g "daemon off;"
